class Region:
    # Jungle
    JUNGLE = "Jungle"
    JUNGLE_SHOP = "Jungle Shop"
    JUNGLE_HIJINXS = "Jungle Hijinxs"
    KING_OF_CLING = "King of Cling"
    TREE_TOP_BOP = "Tree Top Bop"
    SUNSET_SHORE = "Sunset Shore"
    CANOPY_CANNONS = "Canopy Cannons"
    CRAZY_CART = "Crazy Cart"
    MUGLYS_MOUND = "Mugly's Mound"
    PLATFORM_PANIC = "Platform Panic"

    # Beach
    BEACH = "Beach"
    BEACH_SHOP = "Beach Shop"
    POPPIN_PLANKS = "Poppin' Planks"
    SLOPPY_SANDS = "Sloppy Sands"
    PEACEFUL_PIER = "Peaceful Pier"
    CANNON_CLUSTER = "Cannon Cluster"
    STORMY_SHORE = "Stormy Shore"
    BLOWHOLE_BOUND = "Blowhole Bound"
    TIDAL_TERROR = "Tidal Terror"
    PINCHIN_PIRATES = "Pinchin' Pirates"
    TUMBLIN_TEMPLE = "Tumblin' Temple"

    # Ruins
    RUINS = "Ruins"
    RUINS_SHOP = "Ruins Shop"
    WONKY_WATERWAY = "Wonky Waterway"
    BUTTON_BASH = "Button Bash"
    MAST_BLAST = "Mast Blast"
    DAMP_DUNGEON = "Damp Dungeon"
    ITTY_BITTY_BITERS = "Itty Bitty Biters"
    TEMPLE_TOPPLE = "Temple Topple"
    RUINED_ROOST = "Ruined Roost"
    SHIFTY_SMASHERS = "Shifty Smashers"

    # Cave
    CAVE = "Cave"
    CAVE_SHOP = "Cave Shop"
    RICKETY_RAILS = "Rickety Rails"
    GRIP_N_TRIP = "Grip 'n' Trip"
    BOMBS_AWAY = "Bombs Away"
    MOLE_PATROL = "Mole Patrol"
    CROWDED_CAVERN = "Crowded Cavern"
    THE_MOLE_TRAIN = "The Mole Train"
    JAGGED_JEWELS = "Jagged Jewels"

    # Forest
    FOREST = "Forest"
    FOREST_SHOP = "Forest Shop"
    VINE_VALLEY = "Vine Valley"
    CLINGY_SWINGY = "Clingy Swingy"
    FLUTTER_FLYAWAY = "Flutter Flyaway"
    TIPPIN_TOTEMS = "Tippin' Totems"
    LONGSHOT_LAUNCH = "Longshot Launch"
    SPRINGY_SPORES = "Springy Spores"
    WIGGLEVINE_WONDERS = "Wigglevine Wonders"
    MUNCHER_MARATHON = "Muncher Marathon"
    MANGORUBY_RUN = "Mangoruby Run"
    BLAST_N_BOUNCE = "Blast 'n' Bounce"

    # Cliff
    CLIFF = "Cliff"
    CLIFF_SHOP = "Cliff Shop"
    STICKY_SITUATION = "Sticky Situation"
    PREHISTORIC_PATH = "Prehistoric Path"
    WEIGHTY_WAY = "Weighty Way"
    BOULDER_ROLLER = "Boulder Roller"
    PRECARIOUS_PLATEAU = "Precarious Plateau"
    CRUMBLE_CANYON = "Crumble Canyon"
    TIPPY_SHIPPY = "Tippy Shippy"
    CLIFFTOP_CLIMB = "Clifftop Climb"
    THUGLYS_HIGHRISE = "Thugly's Highrise"
    PERILOUS_PASSAGE = "Perilous Passage"

    # Factory
    FACTORY = "Factory"
    FACTORY_SHOP = "Factory Shop"
    FOGGY_FUMES = "Foggy Fumes"
    SLAMMIN_STEEL = "Slammin' Steel"
    HANDY_HAZARDS = "Handy Hazards"
    GEAR_GETAWAY = "Gear Getaway"
    COG_JOG = "Cog Jog"
    SWITCHEROO = "Switcheroo"
    MUSIC_MADNESS = "Music Madness"
    LIFT_OFF_LAUNCH = "Lift-Off Launch"
    FEATHER_FIEND = "Feather Fiend"
    TREACHEROUS_TRACK = "Treacherous Track"

    # Volcano
    VOLCANO = "Volcano"
    VOLCANO_SHOP = "Volcano Shop"
    FURIOUS_FIRE = "Furious Fire"
    HOT_ROCKET = "Hot Rocket"
    ROASTING_RAILS = "Roasting Rails"
    SMOKEY_PEAK = "Smokey Peak"
    BOBBING_BASALT = "Bobbing Basalt"
    MOVING_MELTERS = "Moving Melters"
    RED_RED_RISING = "Red Red Rising"
    TIKI_TONG_TERROR = "Tiki Tong Terror"
    FIVE_MONKEY_TRIAL = "Five Monkey Trial"

    # Golden Temple
    GOLDEN_TEMPLE = "Golden Temple"

class RegionConnection:
    # Jungle
    JUNGLE_TO_JUNGLE_HIJINXS = "Jungle to Jungle Hijinxs"
    JUNGLE_TO_KING_OF_CLING = "Jungle to King of Cling"
    JUNGLE_TO_TREE_TOP_BOP = "Jungle to Tree Top Bop"
    JUNGLE_TO_SUNSET_SHORE = "Jungle to Sunset Shore"
    JUNGLE_TO_CANOPY_CANNONS = "Jungle to Canopy Cannons"
    JUNGLE_TO_CRAZY_CART = "Jungle to Crazy Cart"
    JUNGLE_TO_MUGLYS_MOUND = "Jungle to Mugly's Mound"
    JUNGLE_TO_PLATFORM_PANIC = "Jungle to Platform Panic"
    JUNGLE_TO_JUNGLE_SHOP = "Jungle to Jungle Shop"

    MUGLYS_MOUND_TO_BEACH = "Mugly's Mound to Beach"

    # Beach
    BEACH_TO_POPPIN_PLANKS = "Beach to Poppin' Planks"
    BEACH_TO_SLOPPY_SANDS = "Beach to Sloppy Sands"
    BEACH_TO_PEACEFUL_PIER = "Beach to Peaceful Pier"
    BEACH_TO_CANNON_CLUSTER = "Beach to Cannon Cluster"
    BEACH_TO_STORMY_SHORE = "Beach to Stormy Shore"
    BEACH_TO_BLOWHOLE_BOUND = "Beach to Blowhole Bound"
    BEACH_TO_TIDAL_TERROR = "Beach to Tidal Terror"
    BEACH_TO_PINCHIN_PIRATES = "Beach to Pinchin' Pirates"
    BEACH_TO_TUMBLIN_TEMPLE = "Beach to Tumblin' Temple"
    BEACH_TO_BEACH_SHOP = "Beach to Beach Shop"

    PINCHIN_PIRATES_TO_RUINS = "Pinchin' Pirates to Ruins"

    # Ruins
    RUINS_TO_WONKY_WATERWAY = "Ruins to Wonky Waterway"
    RUINS_TO_BUTTON_BASH = "Ruins to Button Bash"
    RUINS_TO_MAST_BLAST = "Ruins to Mast Blast"
    RUINS_TO_DAMP_DUNGEON = "Ruins to Damp Dungeon"
    RUINS_TO_ITTY_BITTY_BITERS = "Ruins to Itty Bitty Biters"
    RUINS_TO_TEMPLE_TOPPLE = "Ruins to Temple Topple"
    RUINS_TO_RUINED_ROOST = "Ruins to Ruined Roost"
    RUINS_TO_SHIFTY_SMASHERS = "Ruins to Shifty Smashers"
    RUINS_TO_RUINS_SHOP = "Ruins to Ruins Shop"

    RUINED_ROOST_TO_CAVE = "Ruined Roost to Cave"

    # Cave
    CAVE_TO_RICKETY_RAILS = "Cave to Rickety Rails"
    CAVE_TO_GRIP_N_TRIP = "Cave to Grip 'n' Trip"
    CAVE_TO_BOMBS_AWAY = "Cave to Bombs Away"
    CAVE_TO_MOLE_PATROL = "Cave to Mole Patrol"
    CAVE_TO_CROWDED_CAVERN = "Cave to Crowded Cavern"
    CAVE_TO_THE_MOLE_TRAIN = "Cave to The Mole Train"
    CAVE_TO_JAGGED_JEWELS = "Cave to Jagged Jewels"
    CAVE_TO_CAVE_SHOP = "Cave to Cave Shop"

    THE_MOLE_TRAIN_TO_FOREST = "The Mole Train to Forest"

    # Forest
    FOREST_TO_VINE_VALLEY = "Forest to Vine Valley"
    FOREST_TO_CLINGY_SWINGY = "Forest to Clingy Swingy"
    FOREST_TO_FLUTTER_FLYAWAY = "Forest to Flutter Flyaway"
    FOREST_TO_TIPPIN_TOTEMS = "Forest to Tippin' Totems"
    FOREST_TO_LONGSHOT_LAUNCH = "Forest to Longshot Launch"
    FOREST_TO_SPRINGY_SPORES = "Forest to Springy Spores"
    FOREST_TO_WIGGLEVINE_WONDERS = "Forest to Wigglevine Wonders"
    FOREST_TO_MUNCHER_MARATHON = "Forest to Muncher Marathon"
    FOREST_TO_MANGORUBY_RUN = "Forest to Mangoruby Run"
    FOREST_TO_BLAST_N_BOUNCE = "Forest to Blast 'n' Bounce"
    FOREST_TO_FOREST_SHOP = "Forest to Forest Shop"

    MANGORUBY_RUN_TO_CLIFF = "Mangoruby Run to Cliff"

    # Cliff
    CLIFF_TO_STICKY_SITUATION = "Cliff to Sticky Situation"
    CLIFF_TO_PREHISTORIC_PATH = "Cliff to Prehistoric Path"
    CLIFF_TO_WEIGHTY_WAY = "Cliff to Weighty Way"
    CLIFF_TO_BOULDER_ROLLER = "Cliff to Boulder Roller"
    CLIFF_TO_PRECARIOUS_PLATEAU = "Cliff to Precarious Plateau"
    CLIFF_TO_CRUMBLE_CANYON = "Cliff to Crumble Canyon"
    CLIFF_TO_TIPPY_SHIPPY = "Cliff to Tippy Shippy"
    CLIFF_TO_CLIFFTOP_CLIMB = "Cliff to Clifftop Climb"
    CLIFF_TO_THUGLYS_HIGHRISE = "Cliff to Thugly's Highrise"
    CLIFF_TO_PERILOUS_PASSAGE = "Cliff to Perilous Passage"
    CLIFF_TO_CLIFF_SHOP = "Cliff to Cliff Shop"

    THUGLYS_HIGHRISE_TO_FACTORY = "Thugly's Highrise to Factory"

    # Factory
    FACTORY_TO_FOGGY_FUMES = "Factory to Foggy Fumes"
    FACTORY_TO_SLAMMIN_STEEL = "Factory to Slammin' Steel"
    FACTORY_TO_HANDY_HAZARDS = "Factory to Handy Hazards"
    FACTORY_TO_GEAR_GETAWAY = "Factory to Gear Getaway"
    FACTORY_TO_COG_JOG = "Factory to Cog Jog"
    FACTORY_TO_SWITCHEROO = "Factory to Switcheroo"
    FACTORY_TO_MUSIC_MADNESS = "Factory to Music Madness"
    FACTORY_TO_LIFT_OFF_LAUNCH = "Factory to Lift-Off Launch"
    FACTORY_TO_TREACHEROUS_TRACK = "Factory to Treacherous Track"
    FACTORY_TO_FACTORY_SHOP = "Factory to Factory Shop"

    LIFT_OFF_LAUNCH_TO_FEATHER_FIEND = "Lift-Off Launch to Feather Fiend"

    FEATHER_FIEND_TO_VOLCANO = "Feather Fiend to Volcano"

    # Volcano
    VOLCANO_TO_FURIOUS_FIRE = "Volcano to Furious Fire"
    VOLCANO_TO_HOT_ROCKET = "Volcano to Hot Rocket"
    VOLCANO_TO_ROASTING_RAILS = "Volcano to Roasting Rails"
    VOLCANO_TO_SMOKEY_PEAK = "Volcano to Smokey Peak"
    VOLCANO_TO_BOBBING_BASALT = "Volcano to Bobbing Basalt"
    VOLCANO_TO_MOVING_MELTERS = "Volcano to Moving Melters"
    VOLCANO_TO_RED_RED_RISING = "Volcano to Red Red Rising"
    VOLCANO_TO_TIKI_TONG_TERROR = "Volcano to Tiki Tong Terror"
    VOLCANO_TO_FIVE_MONKEY_TRIAL = "Volcano to Five Monkey Trial"
    VOLCANO_TO_VOLCANO_SHOP = "Volcano to Volcano Shop"

    TIKI_TONG_TERROR_TO_GOLDEN_TEMPLE = "Tiki Tong Terror to Golden Temple"

class Location:
    JUNGLE_PUZZLE_BUNDLE = "Jungle Puzzle Bundle"
    JUNGLE_KONG_BUNDLE = "Jungle Kong Bundle"
    JUNGLE_CLEARED = "Jungle cleared"
    JUNGLE_CLEARED_MIRROR = "Jungle cleared (Mirror)"
    JUNGLE_CLEARED_TIME_TRIAL_BRONZE = "Jungle cleared (Time Trial) [Bronze]"
    JUNGLE_CLEARED_TIME_TRIAL_SILVER = "Jungle cleared (Time Trial) [Silver]"
    JUNGLE_CLEARED_TIME_TRIAL_GOLD = "Jungle cleared (Time Trial) [Gold]"
    JUNGLE_SHOP_KEY = "Jungle Shop Key"
    JUNGLE_SHOP_BALLOONSX1 = "Jungle Shop Ballon x 1"
    JUNGLE_SHOP_BALLOONSX3 = "Jungle Shop Ballon x 3"
    JUNGLE_SHOP_BALLOONSX7 = "Jungle Shop Ballon x 7"

    JUNGLE_HIJINXS_PUZZLE_PIECE_1 = "1-1 Jungle Hijinxs Puzzle Piece (1)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_2 = "1-1 Jungle Hijinxs Puzzle Piece (2)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_3 = "1-1 Jungle Hijinxs Puzzle Piece (3)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_4 = "1-1 Jungle Hijinxs Puzzle Piece (4)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_5 = "1-1 Jungle Hijinxs Puzzle Piece (5)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_6 = "1-1 Jungle Hijinxs Puzzle Piece (6)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_7 = "1-1 Jungle Hijinxs Puzzle Piece (7)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_8 = "1-1 Jungle Hijinxs Puzzle Piece (8)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_9 = "1-1 Jungle Hijinxs Puzzle Piece (9)"
    JUNGLE_HIJINXS_PUZZLE_PIECE_SET = "1-1 Jungle Hijinxs Puzzle Piece Set"
    JUNGLE_HIJINXS_KONG_LETTER_K = "1-1 Jungle Hijinxs Kong Letter (K)"
    JUNGLE_HIJINXS_KONG_LETTER_O = "1-1 Jungle Hijinxs Kong Letter (O)"
    JUNGLE_HIJINXS_KONG_LETTER_N = "1-1 Jungle Hijinxs Kong Letter (N)"
    JUNGLE_HIJINXS_KONG_LETTER_G = "1-1 Jungle Hijinxs Kong Letter (G)"
    JUNGLE_HIJINXS_KONG_LETTER_SET = "1-1 Jungle Hijinxs Kong Letter Set"
    JUNGLE_HIJINXS_CLEARED = "1-1 Jungle Hijinxs cleared"
    JUNGLE_HIJINXS_CLEARED_MIRROR = "1-1 Jungle Hijinxs cleared (Mirror)"
    JUNGLE_HIJINXS_CLEARED_TIME_TRIAL_BRONZE = "1-1 Jungle Hijinxs cleared (Time Trial) [Bronze]"
    JUNGLE_HIJINXS_CLEARED_TIME_TRIAL_SILVER = "1-1 Jungle Hijinxs cleared (Time Trial) [Silver]"
    JUNGLE_HIJINXS_CLEARED_TIME_TRIAL_GOLD = "1-1 Jungle Hijinxs cleared (Time Trial) [Gold]"

    KING_OF_CLING_PUZZLE_PIECE_1 = "1-2 King of Cling Puzzle Piece (1)"
    KING_OF_CLING_PUZZLE_PIECE_2 = "1-2 King of Cling Puzzle Piece (2)"
    KING_OF_CLING_PUZZLE_PIECE_3 = "1-2 King of Cling Puzzle Piece (3)"
    KING_OF_CLING_PUZZLE_PIECE_4 = "1-2 King of Cling Puzzle Piece (4)"
    KING_OF_CLING_PUZZLE_PIECE_5 = "1-2 King of Cling Puzzle Piece (5)"
    KING_OF_CLING_PUZZLE_PIECE_6 = "1-2 King of Cling Puzzle Piece (6)"
    KING_OF_CLING_PUZZLE_PIECE_7 = "1-2 King of Cling Puzzle Piece (7)"
    KING_OF_CLING_PUZZLE_PIECE_SET = "1-2 King of Cling Puzzle Piece Set"
    KING_OF_CLING_KONG_LETTER_K = "1-2 King of Cling Kong Letter (K)"
    KING_OF_CLING_KONG_LETTER_O = "1-2 King of Cling Kong Letter (O)"
    KING_OF_CLING_KONG_LETTER_N = "1-2 King of Cling Kong Letter (N)"
    KING_OF_CLING_KONG_LETTER_G = "1-2 King of Cling Kong Letter (G)"
    KING_OF_CLING_KONG_LETTER_SET = "1-2 King of Cling Kong Letter Set"
    KING_OF_CLING_CLEARED = "1-2 King of Cling cleared"
    KING_OF_CLING_CLEARED_MIRROR = "1-2 King of Cling cleared (Mirror)"
    KING_OF_CLING_CLEARED_TIME_TRIAL_BRONZE = "1-2 King of Cling cleared (Time Trial) [Bronze]"
    KING_OF_CLING_CLEARED_TIME_TRIAL_SILVER = "1-2 King of Cling cleared (Time Trial) [Silver]"
    KING_OF_CLING_CLEARED_TIME_TRIAL_GOLD = "1-2 King of Cling cleared (Time Trial) [Gold]"

    TREE_TOP_BOP_PUZZLE_PIECE_1 = "1-3 Tree Top Bop Puzzle Piece (1)"
    TREE_TOP_BOP_PUZZLE_PIECE_2 = "1-3 Tree Top Bop Puzzle Piece (2)"
    TREE_TOP_BOP_PUZZLE_PIECE_3 = "1-3 Tree Top Bop Puzzle Piece (3)"
    TREE_TOP_BOP_PUZZLE_PIECE_4 = "1-3 Tree Top Bop Puzzle Piece (4)"
    TREE_TOP_BOP_PUZZLE_PIECE_5 = "1-3 Tree Top Bop Puzzle Piece (5)"
    TREE_TOP_BOP_PUZZLE_PIECE_SET = "1-3 Tree Top Bop Puzzle Piece Set"
    TREE_TOP_BOP_KONG_LETTER_K = "1-3 Tree Top Bop Kong Letter (K)"
    TREE_TOP_BOP_KONG_LETTER_O = "1-3 Tree Top Bop Kong Letter (O)"
    TREE_TOP_BOP_KONG_LETTER_N = "1-3 Tree Top Bop Kong Letter (N)"
    TREE_TOP_BOP_KONG_LETTER_G = "1-3 Tree Top Bop Kong Letter (G)"
    TREE_TOP_BOP_KONG_LETTER_SET = "1-3 Tree Top Bop Kong Letter Set"
    TREE_TOP_BOP_CLEARED = "1-3 Tree Top Bop cleared"
    TREE_TOP_BOP_CLEARED_MIRROR = "1-3 Tree Top Bop cleared (Mirror)"
    TREE_TOP_BOP_CLEARED_TIME_TRIAL_BRONZE = "1-3 Tree Top Bop cleared (Time Trial) [Bronze]"
    TREE_TOP_BOP_CLEARED_TIME_TRIAL_SILVER = "1-3 Tree Top Bop cleared (Time Trial) [Silver]"
    TREE_TOP_BOP_CLEARED_TIME_TRIAL_GOLD = "1-3 Tree Top Bop cleared (Time Trial) [Gold]"

    SUNSET_SHORE_PUZZLE_PIECE_1 = "1-4 Sunset Shore Puzzle Piece (1)"
    SUNSET_SHORE_PUZZLE_PIECE_2 = "1-4 Sunset Shore Puzzle Piece (2)"
    SUNSET_SHORE_PUZZLE_PIECE_3 = "1-4 Sunset Shore Puzzle Piece (3)"
    SUNSET_SHORE_PUZZLE_PIECE_4 = "1-4 Sunset Shore Puzzle Piece (4)"
    SUNSET_SHORE_PUZZLE_PIECE_5 = "1-4 Sunset Shore Puzzle Piece (5)"
    SUNSET_SHORE_PUZZLE_PIECE_SET = "1-4 Sunset Shore Puzzle Piece Set"
    SUNSET_SHORE_KONG_LETTER_K = "1-4 Sunset Shore Kong Letter (K)"
    SUNSET_SHORE_KONG_LETTER_O = "1-4 Sunset Shore Kong Letter (O)"
    SUNSET_SHORE_KONG_LETTER_N = "1-4 Sunset Shore Kong Letter (N)"
    SUNSET_SHORE_KONG_LETTER_G = "1-4 Sunset Shore Kong Letter (G)"
    SUNSET_SHORE_KONG_LETTER_SET = "1-4 Sunset Shore Kong Letter Set"
    SUNSET_SHORE_CLEARED = "1-4 Sunset Shore cleared"
    SUNSET_SHORE_CLEARED_MIRROR = "1-4 Sunset Shore cleared (Mirror)"
    SUNSET_SHORE_CLEARED_TIME_TRIAL_BRONZE = "1-4 Sunset Shore cleared (Time Trial) [Bronze]"
    SUNSET_SHORE_CLEARED_TIME_TRIAL_SILVER = "1-4 Sunset Shore cleared (Time Trial) [Silver]"
    SUNSET_SHORE_CLEARED_TIME_TRIAL_GOLD = "1-4 Sunset Shore cleared (Time Trial) [Gold]"

    CANOPY_CANNONS_PUZZLE_PIECE_1 = "1-5 Canopy Cannons Puzzle Piece (1)"
    CANOPY_CANNONS_PUZZLE_PIECE_2 = "1-5 Canopy Cannons Puzzle Piece (2)"
    CANOPY_CANNONS_PUZZLE_PIECE_3 = "1-5 Canopy Cannons Puzzle Piece (3)"
    CANOPY_CANNONS_PUZZLE_PIECE_4 = "1-5 Canopy Cannons Puzzle Piece (4)"
    CANOPY_CANNONS_PUZZLE_PIECE_5 = "1-5 Canopy Cannons Puzzle Piece (5)"
    CANOPY_CANNONS_PUZZLE_PIECE_SET = "1-5 Canopy Cannons Puzzle Piece Set"
    CANOPY_CANNONS_KONG_LETTER_K = "1-5 Canopy Cannons Kong Letter (K)"
    CANOPY_CANNONS_KONG_LETTER_O = "1-5 Canopy Cannons Kong Letter (O)"
    CANOPY_CANNONS_KONG_LETTER_N = "1-5 Canopy Cannons Kong Letter (N)"
    CANOPY_CANNONS_KONG_LETTER_G = "1-5 Canopy Cannons Kong Letter (G)"
    CANOPY_CANNONS_KONG_LETTER_SET = "1-5 Canopy Cannons Kong Letter Set"
    CANOPY_CANNONS_CLEARED = "1-5 Canopy Cannons cleared"
    CANOPY_CANNONS_CLEARED_MIRROR = "1-5 Canopy Cannons cleared (Mirror)"
    CANOPY_CANNONS_CLEARED_TIME_TRIAL_BRONZE = "1-5 Canopy Cannons cleared (Time Trial) [Bronze]"
    CANOPY_CANNONS_CLEARED_TIME_TRIAL_SILVER = "1-5 Canopy Cannons cleared (Time Trial) [Silver]"
    CANOPY_CANNONS_CLEARED_TIME_TRIAL_GOLD = "1-5 Canopy Cannons cleared (Time Trial) [Gold]"

    CRAZY_CART_PUZZLE_PIECE_1 = "1-6 Crazy Cart Puzzle Piece (1)"
    CRAZY_CART_PUZZLE_PIECE_2 = "1-6 Crazy Cart Puzzle Piece (2)"
    CRAZY_CART_PUZZLE_PIECE_3 = "1-6 Crazy Cart Puzzle Piece (3)"
    CRAZY_CART_PUZZLE_PIECE_4 = "1-6 Crazy Cart Puzzle Piece (4)"
    CRAZY_CART_PUZZLE_PIECE_5 = "1-6 Crazy Cart Puzzle Piece (5)"
    CRAZY_CART_PUZZLE_PIECE_SET = "1-6 Crazy_Cart Puzzle Piece Set"
    CRAZY_CART_KONG_LETTER_K = "1-6 Crazy Cart Kong Letter (K)"
    CRAZY_CART_KONG_LETTER_O = "1-6 Crazy Cart Kong Letter (O)"
    CRAZY_CART_KONG_LETTER_N = "1-6 Crazy Cart Kong Letter (N)"
    CRAZY_CART_KONG_LETTER_G = "1-6 Crazy Cart Kong Letter (G)"
    CRAZY_CART_KONG_LETTER_SET = "1-6 Crazy Cart Kong Letter Set"
    CRAZY_CART_CLEARED = "1-6 Crazy Cart cleared"
    CRAZY_CART_CLEARED_MIRROR = "1-6 Crazy Cart cleared (Mirror)"
    CRAZY_CART_CLEARED_TIME_TRIAL_BRONZE = "1-6 Crazy Cart cleared (Time Trial) [Bronze]"
    CRAZY_CART_CLEARED_TIME_TRIAL_SILVER = "1-6 Crazy Cart cleared (Time Trial) [Silver]"
    CRAZY_CART_CLEARED_TIME_TRIAL_GOLD = "1-6 Crazy Cart cleared (Time Trial) [Gold]"

    MUGLYS_MOUND_CLEARED = "1-B Mugly's Mound cleared"
    MUGLYS_MOUND_CLEARED_MIRROR = "1-B Mugly's Mound cleared (Mirror)"
    MUGLYS_MOUND_CLEARED_TIME_TRIAL_BRONZE = "1-B Mugly's Mound cleared (Time Trial) [Bronze]"
    MUGLYS_MOUND_CLEARED_TIME_TRIAL_SILVER = "1-B Mugly's Mound cleared (Time Trial) [Silver]"
    MUGLYS_MOUND_CLEARED_TIME_TRIAL_GOLD = "1-B Mugly's Mound cleared (Time Trial) [Gold]"

    PLATFORM_PANIC_PUZZLE_PIECE_1 = "1-K Platform Panic Puzzle Piece (1)"
    PLATFORM_PANIC_PUZZLE_PIECE_2 = "1-K Platform Panic Puzzle Piece (2)"
    PLATFORM_PANIC_PUZZLE_PIECE_3 = "1-K Platform Panic Puzzle Piece (3)"
    PLATFORM_PANIC_PUZZLE_PIECE_4 = "1-K Platform Panic Puzzle Piece (4)"
    PLATFORM_PANIC_PUZZLE_PIECE_5 = "1-K Platform Panic Puzzle Piece (5)"
    PLATFORM_PANIC_PUZZLE_PIECE_SET = "1-K Platform Panic Puzzle Piece Set"
    PLATFORM_PANIC_CLEARED = "1-K Platform Panic cleared"
    PLATFORM_PANIC_CLEARED_MIRROR = "1-K Platform Panic cleared (Mirror)"
    PLATFORM_PANIC_CLEARED_TIME_TRIAL_BRONZE = "1-K Platform Panic cleared (Time Trial) [Bronze]"
    PLATFORM_PANIC_CLEARED_TIME_TRIAL_SILVER = "1-K Platform Panic cleared (Time Trial) [Silver]"
    PLATFORM_PANIC_CLEARED_TIME_TRIAL_GOLD = "1-K Platform Panic cleared (Time Trial) [Gold]"

    BEACH_PUZZLE_BUNDLE = "Beach Puzzle Bundle"
    BEACH_KONG_BUNDLE = "Beach Kong Bundle"
    BEACH_CLEARED = "Beach cleared"
    BEACH_CLEARED_MIRROR = "Beach cleared (Mirror)"
    BEACH_CLEARED_TIME_TRIAL_BRONZE = "Beach cleared (Time Trial) [Bronze]"
    BEACH_CLEARED_TIME_TRIAL_SILVER = "Beach cleared (Time Trial) [Silver]"
    BEACH_CLEARED_TIME_TRIAL_GOLD = "Beach cleared (Time Trial) [Gold]"
    BEACH_SHOP_KEY = "Beach Shop Key"
    BEACH_SHOP_BALLOONSX1 = "Beach Shop Ballon x 1"
    BEACH_SHOP_BALLOONSX3 = "Beach Shop Ballon x 3"
    BEACH_SHOP_BALLOONSX7 = "Beach Shop Ballon x 7"

    POPPIN_PLANKS_PUZZLE_PIECE_1 = "2-1 Poppin' Planks Puzzle Piece (1)"
    POPPIN_PLANKS_PUZZLE_PIECE_2 = "2-1 Poppin' Planks Puzzle Piece (2)"
    POPPIN_PLANKS_PUZZLE_PIECE_3 = "2-1 Poppin' Planks Puzzle Piece (3)"
    POPPIN_PLANKS_PUZZLE_PIECE_4 = "2-1 Poppin' Planks Puzzle Piece (4)"
    POPPIN_PLANKS_PUZZLE_PIECE_5 = "2-1 Poppin' Planks Puzzle Piece (5)"
    POPPIN_PLANKS_PUZZLE_PIECE_SET = "2-1 Poppin' Planks Puzzle Piece Set"
    POPPIN_PLANKS_KONG_LETTER_K = "2-1 Poppin' Planks Kong Letter (K)"
    POPPIN_PLANKS_KONG_LETTER_O = "2-1 Poppin' Planks Kong Letter (O)"
    POPPIN_PLANKS_KONG_LETTER_N = "2-1 Poppin' Planks Kong Letter (N)"
    POPPIN_PLANKS_KONG_LETTER_G = "2-1 Poppin' Planks Kong Letter (G)"
    POPPIN_PLANKS_KONG_LETTER_SET = "2-1 Poppin' Planks Kong Letter Set"
    POPPIN_PLANKS_CLEARED = "2-1 Poppin' Planks cleared"
    POPPIN_PLANKS_CLEARED_MIRROR = "2-1 Poppin' Planks cleared (Mirror)"
    POPPIN_PLANKS_CLEARED_TIME_TRIAL_BRONZE = "2-1 Poppin' Planks cleared (Time Trial) [Bronze]"
    POPPIN_PLANKS_CLEARED_TIME_TRIAL_SILVER = "2-1 Poppin' Planks cleared (Time Trial) [Silver]"
    POPPIN_PLANKS_CLEARED_TIME_TRIAL_GOLD = "2-1 Poppin' Planks cleared (Time Trial) [Gold]"

    SLOPPY_SANDS_PUZZLE_PIECE_1 = "2-2 Sloppy Sands Puzzle Piece (1)"
    SLOPPY_SANDS_PUZZLE_PIECE_2 = "2-2 Sloppy Sands Puzzle Piece (2)"
    SLOPPY_SANDS_PUZZLE_PIECE_3 = "2-2 Sloppy Sands Puzzle Piece (3)"
    SLOPPY_SANDS_PUZZLE_PIECE_4 = "2-2 Sloppy Sands Puzzle Piece (4)"
    SLOPPY_SANDS_PUZZLE_PIECE_5 = "2-2 Sloppy Sands Puzzle Piece (5)"
    SLOPPY_SANDS_PUZZLE_PIECE_6 = "2-2 Sloppy Sands Puzzle Piece (6)"
    SLOPPY_SANDS_PUZZLE_PIECE_7 = "2-2 Sloppy Sands Puzzle Piece (7)"
    SLOPPY_SANDS_PUZZLE_PIECE_SET = "2-2 Sloppy Sands Puzzle Piece Set"
    SLOPPY_SANDS_KONG_LETTER_K = "2-2 Sloppy Sands Kong Letter (K)"
    SLOPPY_SANDS_KONG_LETTER_O = "2-2 Sloppy Sands Kong Letter (O)"
    SLOPPY_SANDS_KONG_LETTER_N = "2-2 Sloppy Sands Kong Letter (N)"
    SLOPPY_SANDS_KONG_LETTER_G = "2-2 Sloppy Sands Kong Letter (G)"
    SLOPPY_SANDS_KONG_LETTER_SET = "2-2 Sloppy Sands Kong Letter Set"
    SLOPPY_SANDS_CLEARED = "2-2 Sloppy Sands cleared"
    SLOPPY_SANDS_CLEARED_MIRROR = "2-2 Sloppy Sands cleared (Mirror)"
    SLOPPY_SANDS_CLEARED_TIME_TRIAL_BRONZE = "2-2 Sloppy Sands cleared (Time Trial) [Bronze]"
    SLOPPY_SANDS_CLEARED_TIME_TRIAL_SILVER = "2-2 Sloppy Sands cleared (Time Trial) [Silver]"
    SLOPPY_SANDS_CLEARED_TIME_TRIAL_GOLD = "2-2 Sloppy Sands cleared (Time Trial) [Gold]"

    PEACEFUL_PIER_PUZZLE_PIECE_1 = "2-3 Peaceful Pier Puzzle Piece (1)"
    PEACEFUL_PIER_PUZZLE_PIECE_2 = "2-3 Peaceful Pier Puzzle Piece (2)"
    PEACEFUL_PIER_PUZZLE_PIECE_3 = "2-3 Peaceful Pier Puzzle Piece (3)"
    PEACEFUL_PIER_PUZZLE_PIECE_4 = "2-3 Peaceful Pier Puzzle Piece (4)"
    PEACEFUL_PIER_PUZZLE_PIECE_5 = "2-3 Peaceful Pier Puzzle Piece (5)"
    PEACEFUL_PIER_PUZZLE_PIECE_SET = "2-3 Peaceful Pier Puzzle Piece Set"
    PEACEFUL_PIER_KONG_LETTER_K = "2-3 Peaceful Pier Kong Letter (K)"
    PEACEFUL_PIER_KONG_LETTER_O = "2-3 Peaceful Pier Kong Letter (O)"
    PEACEFUL_PIER_KONG_LETTER_N = "2-3 Peaceful Pier Kong Letter (N)"
    PEACEFUL_PIER_KONG_LETTER_G = "2-3 Peaceful Pier Kong Letter (G)"
    PEACEFUL_PIER_KONG_LETTER_SET = "2-3 Peaceful Pier Kong Letter Set"
    PEACEFUL_PIER_CLEARED = "2-3 Peaceful Pier cleared"
    PEACEFUL_PIER_CLEARED_MIRROR = "2-3 Peaceful Pier cleared (Mirror)"
    PEACEFUL_PIER_CLEARED_TIME_TRIAL_BRONZE = "2-3 Peaceful Pier cleared (Time Trial) [Bronze]"
    PEACEFUL_PIER_CLEARED_TIME_TRIAL_SILVER = "2-3 Peaceful Pier cleared (Time Trial) [Silver]"
    PEACEFUL_PIER_CLEARED_TIME_TRIAL_GOLD = "2-3 Peaceful Pier cleared (Time Trial) [Gold]"

    CANNON_CLUSTER_PUZZLE_PIECE_1 = "2-4 Cannon Cluster Puzzle Piece (1)"
    CANNON_CLUSTER_PUZZLE_PIECE_2 = "2-4 Cannon Cluster Puzzle Piece (2)"
    CANNON_CLUSTER_PUZZLE_PIECE_3 = "2-4 Cannon Cluster Puzzle Piece (3)"
    CANNON_CLUSTER_PUZZLE_PIECE_4 = "2-4 Cannon Cluster Puzzle Piece (4)"
    CANNON_CLUSTER_PUZZLE_PIECE_5 = "2-4 Cannon Cluster Puzzle Piece (5)"
    CANNON_CLUSTER_PUZZLE_PIECE_6 = "2-4 Cannon Cluster Puzzle Piece (6)"
    CANNON_CLUSTER_PUZZLE_PIECE_7 = "2-4 Cannon Cluster Puzzle Piece (7)"
    CANNON_CLUSTER_PUZZLE_PIECE_SET = "2-4 Cannon Cluster Puzzle Piece Set"
    CANNON_CLUSTER_KONG_LETTER_K = "2-4 Cannon Cluster Kong Letter (K)"
    CANNON_CLUSTER_KONG_LETTER_O = "2-4 Cannon Cluster Kong Letter (O)"
    CANNON_CLUSTER_KONG_LETTER_N = "2-4 Cannon Cluster Kong Letter (N)"
    CANNON_CLUSTER_KONG_LETTER_G = "2-4 Cannon Cluster Kong Letter (G)"
    CANNON_CLUSTER_KONG_LETTER_SET = "2-4 Cannon Cluster Kong Letter Set"
    CANNON_CLUSTER_CLEARED = "2-4 Cannon Cluster cleared"
    CANNON_CLUSTER_CLEARED_MIRROR = "2-4 Cannon Cluster cleared (Mirror)"
    CANNON_CLUSTER_CLEARED_TIME_TRIAL_BRONZE = "2-4 Cannon Cluster cleared (Time Trial) [Bronze]"
    CANNON_CLUSTER_CLEARED_TIME_TRIAL_SILVER = "2-4 Cannon Cluster cleared (Time Trial) [Silver]"
    CANNON_CLUSTER_CLEARED_TIME_TRIAL_GOLD = "2-4 Cannon Cluster cleared (Time Trial) [Gold]"

    STORMY_SHORE_PUZZLE_PIECE_1 = "2-5 Stormy Shore Puzzle Piece (1)"
    STORMY_SHORE_PUZZLE_PIECE_2 = "2-5 Stormy Shore Puzzle Piece (2)"
    STORMY_SHORE_PUZZLE_PIECE_3 = "2-5 Stormy Shore Puzzle Piece (3)"
    STORMY_SHORE_PUZZLE_PIECE_4 = "2-5 Stormy Shore Puzzle Piece (4)"
    STORMY_SHORE_PUZZLE_PIECE_5 = "2-5 Stormy Shore Puzzle Piece (5)"
    STORMY_SHORE_PUZZLE_PIECE_SET = "2-5 Stormy Shore Puzzle Piece Set"
    STORMY_SHORE_KONG_LETTER_K = "2-5 Stormy Shore Kong Letter (K)"
    STORMY_SHORE_KONG_LETTER_O = "2-5 Stormy Shore Kong Letter (O)"
    STORMY_SHORE_KONG_LETTER_N = "2-5 Stormy Shore Kong Letter (N)"
    STORMY_SHORE_KONG_LETTER_G = "2-5 Stormy Shore Kong Letter (G)"
    STORMY_SHORE_KONG_LETTER_SET = "2-5 Stormy Shore Kong Letter Set"
    STORMY_SHORE_CLEARED = "2-5 Stormy Shore cleared"
    STORMY_SHORE_CLEARED_MIRROR = "2-5 Stormy Shore cleared (Mirror)"
    STORMY_SHORE_CLEARED_TIME_TRIAL_BRONZE = "2-5 Stormy Shore cleared (Time Trial) [Bronze]"
    STORMY_SHORE_CLEARED_TIME_TRIAL_SILVER = "2-5 Stormy Shore cleared (Time Trial) [Silver]"
    STORMY_SHORE_CLEARED_TIME_TRIAL_GOLD = "2-5 Stormy Shore cleared (Time Trial) [Gold]"

    BLOWHOLE_BOUND_PUZZLE_PIECE_1 = "2-6 Blowhole Bound Puzzle Piece (1)"
    BLOWHOLE_BOUND_PUZZLE_PIECE_2 = "2-6 Blowhole Bound Puzzle Piece (2)"
    BLOWHOLE_BOUND_PUZZLE_PIECE_3 = "2-6 Blowhole Bound Puzzle Piece (3)"
    BLOWHOLE_BOUND_PUZZLE_PIECE_4 = "2-6 Blowhole Bound Puzzle Piece (4)"
    BLOWHOLE_BOUND_PUZZLE_PIECE_5 = "2-6 Blowhole Bound Puzzle Piece (5)"
    BLOWHOLE_BOUND_PUZZLE_PIECE_SET = "2-6 Blowhole Bound Puzzle Piece Set"
    BLOWHOLE_BOUND_KONG_LETTER_K = "2-6 Blowhole Bound Kong Letter (K)"
    BLOWHOLE_BOUND_KONG_LETTER_O = "2-6 Blowhole Bound Kong Letter (O)"
    BLOWHOLE_BOUND_KONG_LETTER_N = "2-6 Blowhole Bound Kong Letter (N)"
    BLOWHOLE_BOUND_KONG_LETTER_G = "2-6 Blowhole Bound Kong Letter (G)"
    BLOWHOLE_BOUND_KONG_LETTER_SET = "2-6 Blowhole Bound Kong Letter Set"
    BLOWHOLE_BOUND_CLEARED = "2-6 Blowhole Bound cleared"
    BLOWHOLE_BOUND_CLEARED_MIRROR = "2-6 Blowhole Bound cleared (Mirror)"
    BLOWHOLE_BOUND_CLEARED_TIME_TRIAL_BRONZE = "2-6 Blowhole Bound cleared (Time Trial) [Bronze]"
    BLOWHOLE_BOUND_CLEARED_TIME_TRIAL_SILVER = "2-6 Blowhole Bound cleared (Time Trial) [Silver]"
    BLOWHOLE_BOUND_CLEARED_TIME_TRIAL_GOLD = "2-6 Blowhole Bound cleared (Time Trial) [Gold]"

    TIDAL_TERROR_PUZZLE_PIECE_1 = "2-7 Tidal Terror Puzzle Piece (1)"
    TIDAL_TERROR_PUZZLE_PIECE_2 = "2-7 Tidal Terror Puzzle Piece (2)"
    TIDAL_TERROR_PUZZLE_PIECE_3 = "2-7 Tidal Terror Puzzle Piece (3)"
    TIDAL_TERROR_PUZZLE_PIECE_4 = "2-7 Tidal Terror Puzzle Piece (4)"
    TIDAL_TERROR_PUZZLE_PIECE_5 = "2-7 Tidal Terror Puzzle Piece (5)"
    TIDAL_TERROR_PUZZLE_PIECE_SET = "2-7 Tidal Terror Puzzle Piece Set"
    TIDAL_TERROR_KONG_LETTER_K = "2-7 Tidal Terror Kong Letter (K)"
    TIDAL_TERROR_KONG_LETTER_O = "2-7 Tidal Terror Kong Letter (O)"
    TIDAL_TERROR_KONG_LETTER_N = "2-7 Tidal Terror Kong Letter (N)"
    TIDAL_TERROR_KONG_LETTER_G = "2-7 Tidal Terror Kong Letter (G)"
    TIDAL_TERROR_KONG_LETTER_SET = "2-7 Tidal Terror Kong Letter Set"
    TIDAL_TERROR_CLEARED = "2-7 Tidal Terror cleared"
    TIDAL_TERROR_CLEARED_MIRROR = "2-7 Tidal Terror cleared (Mirror)"
    TIDAL_TERROR_CLEARED_TIME_TRIAL_BRONZE = "2-7 Tidal Terror cleared (Time Trial) [Bronze]"
    TIDAL_TERROR_CLEARED_TIME_TRIAL_SILVER = "2-7 Tidal Terror cleared (Time Trial) [Silver]"
    TIDAL_TERROR_CLEARED_TIME_TRIAL_GOLD = "2-7 Tidal Terror cleared (Time Trial) [Gold]"

    PINCHIN_PIRATES_CLEARED = "2-B Pinchin' Pirates cleared"
    PINCHIN_PIRATES_CLEARED_MIRROR = "2-B Pinchin' Pirates cleared (Mirror)"
    PINCHIN_PIRATES_CLEARED_TIME_TRIAL_BRONZE = "2-B Pinchin' Pirates cleared (Time Trial) [Bronze]"
    PINCHIN_PIRATES_CLEARED_TIME_TRIAL_SILVER = "2-B Pinchin' Pirates cleared (Time Trial) [Silver]"
    PINCHIN_PIRATES_CLEARED_TIME_TRIAL_GOLD = "2-B Pinchin' Pirates cleared (Time Trial) [Gold]"

    TUMBLIN_TEMPLE_PUZZLE_PIECE_1 = "2-K Tumblin' Temple Puzzle Piece (1)"
    TUMBLIN_TEMPLE_PUZZLE_PIECE_2 = "2-K Tumblin' Temple Puzzle Piece (2)"
    TUMBLIN_TEMPLE_PUZZLE_PIECE_3 = "2-K Tumblin' Temple Puzzle Piece (3)"
    TUMBLIN_TEMPLE_PUZZLE_PIECE_4 = "2-K Tumblin' Temple Puzzle Piece (4)"
    TUMBLIN_TEMPLE_PUZZLE_PIECE_5 = "2-K Tumblin' Temple Puzzle Piece (5)"
    TUMBLIN_TEMPLE_PUZZLE_PIECE_SET = "2-K Tumblin' Temple Puzzle Piece Set"
    TUMBLIN_TEMPLE_CLEARED = "2-K Tumblin' Temple cleared"
    TUMBLIN_TEMPLE_CLEARED_MIRROR = "2-K Tumblin' Temple cleared (Mirror)"
    TUMBLIN_TEMPLE_CLEARED_TIME_TRIAL_BRONZE = "2-K Tumblin' Temple cleared (Time Trial) [Bronze]"
    TUMBLIN_TEMPLE_CLEARED_TIME_TRIAL_SILVER = "2-K Tumblin' Temple cleared (Time Trial) [Silver]"
    TUMBLIN_TEMPLE_CLEARED_TIME_TRIAL_GOLD = "2-K Tumblin' Temple cleared (Time Trial) [Gold]"

    RUINS_PUZZLE_BUNDLE = "Ruins Puzzle Bundle"
    RUINS_KONG_BUNDLE = "Ruins Kong Bundle"
    RUINS_CLEARED = "Ruins cleared"
    RUINS_CLEARED_MIRROR = "Ruins cleared (Mirror)"
    RUINS_CLEARED_TIME_TRIAL_BRONZE = "Ruins cleared (Time Trial) [Bronze]"
    RUINS_CLEARED_TIME_TRIAL_SILVER = "Ruins cleared (Time Trial) [Silver]"
    RUINS_CLEARED_TIME_TRIAL_GOLD = "Ruins cleared (Time Trial) [Gold]"
    RUINS_SHOP_KEY = "Ruins Shop Key"
    RUINS_SHOP_BALLOONSX1 = "Ruins Shop Ballon x 1"
    RUINS_SHOP_BALLOONSX3 = "Ruins Shop Ballon x 3"
    RUINS_SHOP_BALLOONSX7 = "Ruins Shop Ballon x 7"

    WONKY_WATERWAY_PUZZLE_PIECE_1 = "3-1 Wonky Waterway Puzzle Piece (1)"
    WONKY_WATERWAY_PUZZLE_PIECE_2 = "3-1 Wonky Waterway Puzzle Piece (2)"
    WONKY_WATERWAY_PUZZLE_PIECE_3 = "3-1 Wonky Waterway Puzzle Piece (3)"
    WONKY_WATERWAY_PUZZLE_PIECE_4 = "3-1 Wonky Waterway Puzzle Piece (4)"
    WONKY_WATERWAY_PUZZLE_PIECE_5 = "3-1 Wonky Waterway Puzzle Piece (5)"
    WONKY_WATERWAY_PUZZLE_PIECE_6 = "3-1 Wonky Waterway Puzzle Piece (6)"
    WONKY_WATERWAY_PUZZLE_PIECE_7 = "3-1 Wonky Waterway Puzzle Piece (7)"
    WONKY_WATERWAY_PUZZLE_PIECE_SET = "3-1 Wonky Waterway Puzzle Piece Set"
    WONKY_WATERWAY_KONG_LETTER_K = "3-1 Wonky Waterway Kong Letter (K)"
    WONKY_WATERWAY_KONG_LETTER_O = "3-1 Wonky Waterway Kong Letter (O)"
    WONKY_WATERWAY_KONG_LETTER_N = "3-1 Wonky Waterway Kong Letter (N)"
    WONKY_WATERWAY_KONG_LETTER_G = "3-1 Wonky Waterway Kong Letter (G)"
    WONKY_WATERWAY_KONG_LETTER_SET = "3-1 Wonky Waterway Kong Letter Set"
    WONKY_WATERWAY_CLEARED = "3-1 Wonky Waterway cleared"
    WONKY_WATERWAY_CLEARED_MIRROR = "3-1 Wonky Waterway cleared (Mirror)"
    WONKY_WATERWAY_CLEARED_TIME_TRIAL_BRONZE = "3-1 Wonky Waterway cleared (Time Trial) [Bronze]"
    WONKY_WATERWAY_CLEARED_TIME_TRIAL_SILVER = "3-1 Wonky Waterway cleared (Time Trial) [Silver]"
    WONKY_WATERWAY_CLEARED_TIME_TRIAL_GOLD = "3-1 Wonky Waterway cleared (Time Trial) [Gold]"

    BUTTON_BASH_PUZZLE_PIECE_1 = "3-2 Button Bash Puzzle Piece (1)"
    BUTTON_BASH_PUZZLE_PIECE_2 = "3-2 Button Bash Puzzle Piece (2)"
    BUTTON_BASH_PUZZLE_PIECE_3 = "3-2 Button Bash Puzzle Piece (3)"
    BUTTON_BASH_PUZZLE_PIECE_4 = "3-2 Button Bash Puzzle Piece (4)"
    BUTTON_BASH_PUZZLE_PIECE_5 = "3-2 Button Bash Puzzle Piece (5)"
    BUTTON_BASH_PUZZLE_PIECE_6 = "3-2 Button Bash Puzzle Piece (6)"
    BUTTON_BASH_PUZZLE_PIECE_7 = "3-2 Button Bash Puzzle Piece (7)"
    BUTTON_BASH_PUZZLE_PIECE_SET = "3-2 Button Bash Puzzle Piece Set"
    BUTTON_BASH_KONG_LETTER_K = "3-2 Button Bash Kong Letter (K)"
    BUTTON_BASH_KONG_LETTER_O = "3-2 Button Bash Kong Letter (O)"
    BUTTON_BASH_KONG_LETTER_N = "3-2 Button Bash Kong Letter (N)"
    BUTTON_BASH_KONG_LETTER_G = "3-2 Button Bash Kong Letter (G)"
    BUTTON_BASH_KONG_LETTER_SET = "3-2 Button Bash Kong Letter Set"
    BUTTON_BASH_CLEARED = "3-2 Button Bash cleared"
    BUTTON_BASH_CLEARED_MIRROR = "3-2 Button Bash cleared (Mirror)"
    BUTTON_BASH_CLEARED_TIME_TRIAL_BRONZE = "3-2 Button Bash cleared (Time Trial) [Bronze]"
    BUTTON_BASH_CLEARED_TIME_TRIAL_SILVER = "3-2 Button Bash cleared (Time Trial) [Silver]"
    BUTTON_BASH_CLEARED_TIME_TRIAL_GOLD = "3-2 Button Bash cleared (Time Trial) [Gold]"

    MAST_BLAST_PUZZLE_PIECE_1 = "3-3 Mast Blast Puzzle Piece (1)"
    MAST_BLAST_PUZZLE_PIECE_2 = "3-3 Mast Blast Puzzle Piece (2)"
    MAST_BLAST_PUZZLE_PIECE_3 = "3-3 Mast Blast Puzzle Piece (3)"
    MAST_BLAST_PUZZLE_PIECE_4 = "3-3 Mast Blast Puzzle Piece (4)"
    MAST_BLAST_PUZZLE_PIECE_5 = "3-3 Mast Blast Puzzle Piece (5)"
    MAST_BLAST_PUZZLE_PIECE_6 = "3-3 Mast Blast Puzzle Piece (6)"
    MAST_BLAST_PUZZLE_PIECE_7 = "3-3 Mast Blast Puzzle Piece (7)"
    MAST_BLAST_PUZZLE_PIECE_SET = "3-3 Mast Blast Puzzle Piece Set"
    MAST_BLAST_KONG_LETTER_K = "3-3 Mast Blast Kong Letter (K)"
    MAST_BLAST_KONG_LETTER_O = "3-3 Mast Blast Kong Letter (O)"
    MAST_BLAST_KONG_LETTER_N = "3-3 Mast Blast Kong Letter (N)"
    MAST_BLAST_KONG_LETTER_G = "3-3 Mast Blast Kong Letter (G)"
    MAST_BLAST_KONG_LETTER_SET = "3-3 Mast Blast Kong Letter Set"
    MAST_BLAST_CLEARED = "3-3 Mast Blast cleared"
    MAST_BLAST_CLEARED_MIRROR = "3-3 Mast Blast cleared (Mirror)"
    MAST_BLAST_CLEARED_TIME_TRIAL_BRONZE = "3-3 Mast Blast cleared (Time Trial) [Bronze]"
    MAST_BLAST_CLEARED_TIME_TRIAL_SILVER = "3-3 Mast Blast cleared (Time Trial) [Silver]"
    MAST_BLAST_CLEARED_TIME_TRIAL_GOLD = "3-3 Mast Blast cleared (Time Trial) [Gold]"

    DAMP_DUNGEON_PUZZLE_PIECE_1 = "3-4 Damp Dungeon Puzzle Piece (1)"
    DAMP_DUNGEON_PUZZLE_PIECE_2 = "3-4 Damp Dungeon Puzzle Piece (2)"
    DAMP_DUNGEON_PUZZLE_PIECE_3 = "3-4 Damp Dungeon Puzzle Piece (3)"
    DAMP_DUNGEON_PUZZLE_PIECE_4 = "3-4 Damp Dungeon Puzzle Piece (4)"
    DAMP_DUNGEON_PUZZLE_PIECE_5 = "3-4 Damp Dungeon Puzzle Piece (5)"
    DAMP_DUNGEON_PUZZLE_PIECE_6 = "3-4 Damp Dungeon Puzzle Piece (6)"
    DAMP_DUNGEON_PUZZLE_PIECE_7 = "3-4 Damp Dungeon Puzzle Piece (7)"
    DAMP_DUNGEON_PUZZLE_PIECE_8 = "3-4 Damp Dungeon Puzzle Piece (8)"
    DAMP_DUNGEON_PUZZLE_PIECE_9 = "3-4 Damp Dungeon Puzzle Piece (9)"
    DAMP_DUNGEON_PUZZLE_PIECE_SET = "3-4 Damp Dungeon Puzzle Piece Set"
    DAMP_DUNGEON_KONG_LETTER_K = "3-4 Damp Dungeon Kong Letter (K)"
    DAMP_DUNGEON_KONG_LETTER_O = "3-4 Damp Dungeon Kong Letter (O)"
    DAMP_DUNGEON_KONG_LETTER_N = "3-4 Damp Dungeon Kong Letter (N)"
    DAMP_DUNGEON_KONG_LETTER_G = "3-4 Damp Dungeon Kong Letter (G)"
    DAMP_DUNGEON_KONG_LETTER_SET = "3-4 Damp Dungeon Kong Letter Set"
    DAMP_DUNGEON_CLEARED = "3-4 Damp Dungeon cleared"
    DAMP_DUNGEON_CLEARED_MIRROR = "3-4 Damp Dungeon cleared (Mirror)"
    DAMP_DUNGEON_CLEARED_TIME_TRIAL_BRONZE = "3-4 Damp Dungeon cleared (Time Trial) [Bronze]"
    DAMP_DUNGEON_CLEARED_TIME_TRIAL_SILVER = "3-4 Damp Dungeon cleared (Time Trial) [Silver]"
    DAMP_DUNGEON_CLEARED_TIME_TRIAL_GOLD = "3-4 Damp Dungeon cleared (Time Trial) [Gold]"

    ITTY_BITTY_BITERS_PUZZLE_PIECE_1 = "3-5 Itty Bitty Biters Puzzle Piece (1)"
    ITTY_BITTY_BITERS_PUZZLE_PIECE_2 = "3-5 Itty Bitty Biters Puzzle Piece (2)"
    ITTY_BITTY_BITERS_PUZZLE_PIECE_3 = "3-5 Itty Bitty Biters Puzzle Piece (3)"
    ITTY_BITTY_BITERS_PUZZLE_PIECE_4 = "3-5 Itty Bitty Biters Puzzle Piece (4)"
    ITTY_BITTY_BITERS_PUZZLE_PIECE_5 = "3-5 Itty Bitty Biters Puzzle Piece (5)"
    ITTY_BITTY_BITERS_PUZZLE_PIECE_6 = "3-5 Itty Bitty Biters Puzzle Piece (6)"
    ITTY_BITTY_BITERS_PUZZLE_PIECE_7 = "3-5 Itty Bitty Biters Puzzle Piece (7)"
    ITTY_BITTY_BITERS_PUZZLE_PIECE_SET = "3-5 Itty Bitty Biters Puzzle Piece Set"
    ITTY_BITTY_BITERS_KONG_LETTER_K = "3-5 Itty Bitty Biters Kong Letter (K)"
    ITTY_BITTY_BITERS_KONG_LETTER_O = "3-5 Itty Bitty Biters Kong Letter (O)"
    ITTY_BITTY_BITERS_KONG_LETTER_N = "3-5 Itty Bitty Biters Kong Letter (N)"
    ITTY_BITTY_BITERS_KONG_LETTER_G = "3-5 Itty Bitty Biters Kong Letter (G)"
    ITTY_BITTY_BITERS_KONG_LETTER_SET = "3-5 Itty Bitty Biters Kong Letter Set"
    ITTY_BITTY_BITERS_CLEARED = "3-5 Itty Bitty Biters cleared"
    ITTY_BITTY_BITERS_CLEARED_MIRROR = "3-5 Itty Bitty Biters cleared (Mirror)"
    ITTY_BITTY_BITERS_CLEARED_TIME_TRIAL_BRONZE = "3-5 Itty Bitty Biters cleared (Time Trial) [Bronze]"
    ITTY_BITTY_BITERS_CLEARED_TIME_TRIAL_SILVER = "3-5 Itty Bitty Biters cleared (Time Trial) [Silver]"
    ITTY_BITTY_BITERS_CLEARED_TIME_TRIAL_GOLD = "3-5 Itty Bitty Biters cleared (Time Trial) [Gold]"

    TEMPLE_TOPPLE_PUZZLE_PIECE_1 = "3-6 Temple Topple Puzzle Piece (1)"
    TEMPLE_TOPPLE_PUZZLE_PIECE_2 = "3-6 Temple Topple Puzzle Piece (2)"
    TEMPLE_TOPPLE_PUZZLE_PIECE_3 = "3-6 Temple Topple Puzzle Piece (3)"
    TEMPLE_TOPPLE_PUZZLE_PIECE_4 = "3-6 Temple Topple Puzzle Piece (4)"
    TEMPLE_TOPPLE_PUZZLE_PIECE_5 = "3-6 Temple Topple Puzzle Piece (5)"
    TEMPLE_TOPPLE_PUZZLE_PIECE_SET = "3-6 Temple Topple Puzzle Piece Set"
    TEMPLE_TOPPLE_KONG_LETTER_K = "3-6 Temple Topple Kong Letter (K)"
    TEMPLE_TOPPLE_KONG_LETTER_O = "3-6 Temple Topple Kong Letter (O)"
    TEMPLE_TOPPLE_KONG_LETTER_N = "3-6 Temple Topple Kong Letter (N)"
    TEMPLE_TOPPLE_KONG_LETTER_G = "3-6 Temple Topple Kong Letter (G)"
    TEMPLE_TOPPLE_KONG_LETTER_SET = "3-6 Temple Topple Kong Letter Set"
    TEMPLE_TOPPLE_CLEARED = "3-6 Temple Topple cleared"
    TEMPLE_TOPPLE_CLEARED_MIRROR = "3-6 Temple Topple cleared (Mirror)"
    TEMPLE_TOPPLE_CLEARED_TIME_TRIAL_BRONZE = "3-6 Temple Topple cleared (Time Trial) [Bronze]"
    TEMPLE_TOPPLE_CLEARED_TIME_TRIAL_SILVER = "3-6 Temple Topple cleared (Time Trial) [Silver]"
    TEMPLE_TOPPLE_CLEARED_TIME_TRIAL_GOLD = "3-6 Temple Topple cleared (Time Trial) [Gold]"

    RUINED_ROOST_CLEARED = "3-B Ruined Roost cleared"
    RUINED_ROOST_CLEARED_MIRROR = "3-B Ruined Roost cleared (Mirror)"
    RUINED_ROOST_CLEARED_TIME_TRIAL_BRONZE = "3-B Ruined Roost cleared (Time Trial) [Bronze]"
    RUINED_ROOST_CLEARED_TIME_TRIAL_SILVER = "3-B Ruined Roost cleared (Time Trial) [Silver]"
    RUINED_ROOST_CLEARED_TIME_TRIAL_GOLD = "3-B Ruined Roost cleared (Time Trial) [Gold]"

    SHIFTY_SMASHERS_PUZZLE_PIECE_1 = "3-K Shifty Smashers Puzzle Piece (1)"
    SHIFTY_SMASHERS_PUZZLE_PIECE_2 = "3-K Shifty Smashers Puzzle Piece (2)"
    SHIFTY_SMASHERS_PUZZLE_PIECE_3 = "3-K Shifty Smashers Puzzle Piece (3)"
    SHIFTY_SMASHERS_PUZZLE_PIECE_4 = "3-K Shifty Smashers Puzzle Piece (4)"
    SHIFTY_SMASHERS_PUZZLE_PIECE_5 = "3-K Shifty Smashers Puzzle Piece (5)"
    SHIFTY_SMASHERS_PUZZLE_PIECE_SET = "3-K Shifty Smashers Puzzle Piece Set"
    SHIFTY_SMASHERS_CLEARED = "3-K Shifty Smashers cleared"
    SHIFTY_SMASHERS_CLEARED_MIRROR = "3-K Shifty Smashers cleared (Mirror)"
    SHIFTY_SMASHERS_CLEARED_TIME_TRIAL_BRONZE = "3-K Shifty Smashers cleared (Time Trial) [Bronze]"
    SHIFTY_SMASHERS_CLEARED_TIME_TRIAL_SILVER = "3-K Shifty Smashers cleared (Time Trial) [Silver]"
    SHIFTY_SMASHERS_CLEARED_TIME_TRIAL_GOLD = "3-K Shifty Smashers cleared (Time Trial) [Gold]"

    CAVE_PUZZLE_BUNDLE = "Cave Puzzle Bundle"
    CAVE_KONG_BUNDLE = "Cave Kong Bundle"
    CAVE_CLEARED = "Cave cleared"
    CAVE_CLEARED_MIRROR = "Cave cleared (Mirror)"
    CAVE_CLEARED_TIME_TRIAL_BRONZE = "Cave cleared (Time Trial) [Bronze]"
    CAVE_CLEARED_TIME_TRIAL_SILVER = "Cave cleared (Time Trial) [Silver]"
    CAVE_CLEARED_TIME_TRIAL_GOLD = "Cave cleared (Time Trial) [Gold]"
    CAVE_SHOP_KEY = "Cave Shop Key"
    CAVE_SHOP_BALLOONSX1 = "Cave Shop Ballon x 1"
    CAVE_SHOP_BALLOONSX3 = "Cave Shop Ballon x 3"
    CAVE_SHOP_BALLOONSX7 = "Cave Shop Ballon x 7"

    RICKETY_RAILS_PUZZLE_PIECE_1 = "4-1 Rickety Rails Puzzle Piece (1)"
    RICKETY_RAILS_PUZZLE_PIECE_2 = "4-1 Rickety Rails Puzzle Piece (2)"
    RICKETY_RAILS_PUZZLE_PIECE_3 = "4-1 Rickety Rails Puzzle Piece (3)"
    RICKETY_RAILS_PUZZLE_PIECE_4 = "4-1 Rickety Rails Puzzle Piece (4)"
    RICKETY_RAILS_PUZZLE_PIECE_5 = "4-1 Rickety Rails Puzzle Piece (5)"
    RICKETY_RAILS_PUZZLE_PIECE_SET = "4-1 Rickety Rails Puzzle Piece Set"
    RICKETY_RAILS_KONG_LETTER_K = "4-1 Rickety Rails Kong Letter (K)"
    RICKETY_RAILS_KONG_LETTER_O = "4-1 Rickety Rails Kong Letter (O)"
    RICKETY_RAILS_KONG_LETTER_N = "4-1 Rickety Rails Kong Letter (N)"
    RICKETY_RAILS_KONG_LETTER_G = "4-1 Rickety Rails Kong Letter (G)"
    RICKETY_RAILS_KONG_LETTER_SET = "4-1 Rickety Rails Kong Letter Set"
    RICKETY_RAILS_CLEARED = "4-1 Rickety Rails cleared"
    RICKETY_RAILS_CLEARED_MIRROR = "4-1 Rickety Rails cleared (Mirror)"
    RICKETY_RAILS_CLEARED_TIME_TRIAL_BRONZE = "4-1 Rickety Rails cleared (Time Trial) [Bronze]"
    RICKETY_RAILS_CLEARED_TIME_TRIAL_SILVER = "4-1 Rickety Rails cleared (Time Trial) [Silver]"
    RICKETY_RAILS_CLEARED_TIME_TRIAL_GOLD = "4-1 Rickety Rails cleared (Time Trial) [Gold]"

    GRIP_N_TRIP_PUZZLE_PIECE_1 = "4-2 Grip 'n' Trip Puzzle Piece (1)"
    GRIP_N_TRIP_PUZZLE_PIECE_2 = "4-2 Grip 'n' Trip Puzzle Piece (2)"
    GRIP_N_TRIP_PUZZLE_PIECE_3 = "4-2 Grip 'n' Trip Puzzle Piece (3)"
    GRIP_N_TRIP_PUZZLE_PIECE_4 = "4-2 Grip 'n' Trip Puzzle Piece (4)"
    GRIP_N_TRIP_PUZZLE_PIECE_5 = "4-2 Grip 'n' Trip Puzzle Piece (5)"
    GRIP_N_TRIP_PUZZLE_PIECE_SET = "4-2 Grip 'n' Trip Puzzle Piece Set"
    GRIP_N_TRIP_KONG_LETTER_K = "4-2 Grip 'n' Trip Kong Letter (K)"
    GRIP_N_TRIP_KONG_LETTER_O = "4-2 Grip 'n' Trip Kong Letter (O)"
    GRIP_N_TRIP_KONG_LETTER_N = "4-2 Grip 'n' Trip Kong Letter (N)"
    GRIP_N_TRIP_KONG_LETTER_G = "4-2 Grip 'n' Trip Kong Letter (G)"
    GRIP_N_TRIP_KONG_LETTER_SET = "4-2 Grip 'n' Trip Kong Letter Set"
    GRIP_N_TRIP_CLEARED = "4-2 Grip 'n' Trip cleared"
    GRIP_N_TRIP_CLEARED_MIRROR = "4-2 Grip 'n' Trip cleared (Mirror)"
    GRIP_N_TRIP_CLEARED_TIME_TRIAL_BRONZE = "4-2 Grip 'n' Trip cleared (Time Trial) [Bronze]"
    GRIP_N_TRIP_CLEARED_TIME_TRIAL_SILVER = "4-2 Grip 'n' Trip cleared (Time Trial) [Silver]"
    GRIP_N_TRIP_CLEARED_TIME_TRIAL_GOLD = "4-2 Grip 'n' Trip cleared (Time Trial) [Gold]"

    BOMBS_AWAY_PUZZLE_PIECE_1 = "4-3 Bombs Away Puzzle Piece (1)"
    BOMBS_AWAY_PUZZLE_PIECE_2 = "4-3 Bombs Away Puzzle Piece (2)"
    BOMBS_AWAY_PUZZLE_PIECE_3 = "4-3 Bombs Away Puzzle Piece (3)"
    BOMBS_AWAY_PUZZLE_PIECE_4 = "4-3 Bombs Away Puzzle Piece (4)"
    BOMBS_AWAY_PUZZLE_PIECE_5 = "4-3 Bombs Away Puzzle Piece (5)"
    BOMBS_AWAY_PUZZLE_PIECE_SET = "4-3 Bombs Away Puzzle Piece Set"
    BOMBS_AWAY_KONG_LETTER_K = "4-3 Bombs Away Kong Letter (K)"
    BOMBS_AWAY_KONG_LETTER_O = "4-3 Bombs Away Kong Letter (O)"
    BOMBS_AWAY_KONG_LETTER_N = "4-3 Bombs Away Kong Letter (N)"
    BOMBS_AWAY_KONG_LETTER_G = "4-3 Bombs Away Kong Letter (G)"
    BOMBS_AWAY_KONG_LETTER_SET = "4-3 Bombs Away Kong Letter Set"
    BOMBS_AWAY_CLEARED = "4-3 Bombs Away cleared"
    BOMBS_AWAY_CLEARED_MIRROR = "4-3 Bombs Away cleared (Mirror)"
    BOMBS_AWAY_CLEARED_TIME_TRIAL_BRONZE = "4-3 Bombs Away cleared (Time Trial) [Bronze]"
    BOMBS_AWAY_CLEARED_TIME_TRIAL_SILVER = "4-3 Bombs Away cleared (Time Trial) [Silver]"
    BOMBS_AWAY_CLEARED_TIME_TRIAL_GOLD = "4-3 Bombs Away cleared (Time Trial) [Gold]"

    MOLE_PATROL_PUZZLE_PIECE_1 = "4-4 Mole Patrol Puzzle Piece (1)"
    MOLE_PATROL_PUZZLE_PIECE_2 = "4-4 Mole Patrol Puzzle Piece (2)"
    MOLE_PATROL_PUZZLE_PIECE_3 = "4-4 Mole Patrol Puzzle Piece (3)"
    MOLE_PATROL_PUZZLE_PIECE_4 = "4-4 Mole Patrol Puzzle Piece (4)"
    MOLE_PATROL_PUZZLE_PIECE_5 = "4-4 Mole Patrol Puzzle Piece (5)"
    MOLE_PATROL_PUZZLE_PIECE_SET = "4-4 Mole Patrol Puzzle Piece Set"
    MOLE_PATROL_KONG_LETTER_K = "4-4 Mole Patrol Kong Letter (K)"
    MOLE_PATROL_KONG_LETTER_O = "4-4 Mole Patrol Kong Letter (O)"
    MOLE_PATROL_KONG_LETTER_N = "4-4 Mole Patrol Kong Letter (N)"
    MOLE_PATROL_KONG_LETTER_G = "4-4 Mole Patrol Kong Letter (G)"
    MOLE_PATROL_KONG_LETTER_SET = "4-4 Mole Patrol Kong Letter Set"
    MOLE_PATROL_CLEARED = "4-4 Mole Patrol cleared"
    MOLE_PATROL_CLEARED_MIRROR = "4-4 Mole Patrol cleared (Mirror)"
    MOLE_PATROL_CLEARED_TIME_TRIAL_BRONZE = "4-4 Mole Patrol cleared (Time Trial) [Bronze]"
    MOLE_PATROL_CLEARED_TIME_TRIAL_SILVER = "4-4 Mole Patrol cleared (Time Trial) [Silver]"
    MOLE_PATROL_CLEARED_TIME_TRIAL_GOLD = "4-4 Mole Patrol cleared (Time Trial) [Gold]"

    CROWDED_CAVERN_PUZZLE_PIECE_1 = "4-5 Crowded Cavern Puzzle Piece (1)"
    CROWDED_CAVERN_PUZZLE_PIECE_2 = "4-5 Crowded Cavern Puzzle Piece (2)"
    CROWDED_CAVERN_PUZZLE_PIECE_3 = "4-5 Crowded Cavern Puzzle Piece (3)"
    CROWDED_CAVERN_PUZZLE_PIECE_4 = "4-5 Crowded Cavern Puzzle Piece (4)"
    CROWDED_CAVERN_PUZZLE_PIECE_5 = "4-5 Crowded Cavern Puzzle Piece (5)"
    CROWDED_CAVERN_PUZZLE_PIECE_SET = "4-5 Crowded Cavern Puzzle Piece Set"
    CROWDED_CAVERN_KONG_LETTER_K = "4-5 Crowded Cavern Kong Letter (K)"
    CROWDED_CAVERN_KONG_LETTER_O = "4-5 Crowded Cavern Kong Letter (O)"
    CROWDED_CAVERN_KONG_LETTER_N = "4-5 Crowded Cavern Kong Letter (N)"
    CROWDED_CAVERN_KONG_LETTER_G = "4-5 Crowded Cavern Kong Letter (G)"
    CROWDED_CAVERN_KONG_LETTER_SET = "4-5 Crowded Cavern Kong Letter Set"
    CROWDED_CAVERN_CLEARED = "4-5 Crowded Cavern cleared"
    CROWDED_CAVERN_CLEARED_MIRROR = "4-5 Crowded Cavern cleared (Mirror)"
    CROWDED_CAVERN_CLEARED_TIME_TRIAL_BRONZE = "4-5 Crowded Cavern cleared (Time Trial) [Bronze]"
    CROWDED_CAVERN_CLEARED_TIME_TRIAL_SILVER = "4-5 Crowded Cavern cleared (Time Trial) [Silver]"
    CROWDED_CAVERN_CLEARED_TIME_TRIAL_GOLD = "4-5 Crowded Cavern cleared (Time Trial) [Gold]"

    THE_MOLE_TRAIN_CLEARED = "4-B The Mole Train cleared"
    THE_MOLE_TRAIN_CLEARED_MIRROR = "4-B The Mole Train cleared (Mirror)"
    THE_MOLE_TRAIN_CLEARED_TIME_TRIAL_BRONZE = "4-B The Mole Train cleared (Time Trial) [Bronze]"
    THE_MOLE_TRAIN_CLEARED_TIME_TRIAL_SILVER = "4-B The Mole Train cleared (Time Trial) [Silver]"
    THE_MOLE_TRAIN_CLEARED_TIME_TRIAL_GOLD = "4-B The Mole Train cleared (Time Trial) [Gold]"

    JAGGED_JEWELS_PUZZLE_PIECE_1 = "4-K Jagged Jewels Puzzle Piece (1)"
    JAGGED_JEWELS_PUZZLE_PIECE_2 = "4-K Jagged Jewels Puzzle Piece (2)"
    JAGGED_JEWELS_PUZZLE_PIECE_3 = "4-K Jagged Jewels Puzzle Piece (3)"
    JAGGED_JEWELS_PUZZLE_PIECE_4 = "4-K Jagged Jewels Puzzle Piece (4)"
    JAGGED_JEWELS_PUZZLE_PIECE_5 = "4-K Jagged Jewels Puzzle Piece (5)"
    JAGGED_JEWELS_PUZZLE_PIECE_SET = "4-K Jagged Jewels Puzzle Piece Set"
    JAGGED_JEWELS_CLEARED = "4-K Jagged Jewels cleared"
    JAGGED_JEWELS_CLEARED_MIRROR = "4-K Jagged Jewels cleared (Mirror)"
    JAGGED_JEWELS_CLEARED_TIME_TRIAL_BRONZE = "4-K Jagged Jewels cleared (Time Trial) [Bronze]"
    JAGGED_JEWELS_CLEARED_TIME_TRIAL_SILVER = "4-K Jagged Jewels cleared (Time Trial) [Silver]"
    JAGGED_JEWELS_CLEARED_TIME_TRIAL_GOLD = "4-K Jagged Jewels cleared (Time Trial) [Gold]"

    FOREST_PUZZLE_BUNDLE = "Forest Puzzle Bundle"
    FOREST_KONG_BUNDLE = "Forest Kong Bundle"
    FOREST_CLEARED = "Forest cleared"
    FOREST_CLEARED_MIRROR = "Forest cleared (Mirror)"
    FOREST_CLEARED_TIME_TRIAL_BRONZE = "Forest cleared (Time Trial) [Bronze]"
    FOREST_CLEARED_TIME_TRIAL_SILVER = "Forest cleared (Time Trial) [Silver]"
    FOREST_CLEARED_TIME_TRIAL_GOLD = "Forest cleared (Time Trial) [Gold]"
    FOREST_SHOP_KEY = "Forest Shop Key"
    FOREST_SHOP_BALLOONSX1 = "Forest Shop Ballon x 1"
    FOREST_SHOP_BALLOONSX3 = "Forest Shop Ballon x 3"
    FOREST_SHOP_BALLOONSX7 = "Forest Shop Ballon x 7"


    VINE_VALLEY_PUZZLE_PIECE_1 = "5-1 Vine Valley Puzzle Piece (1)"
    VINE_VALLEY_PUZZLE_PIECE_2 = "5-1 Vine Valley Puzzle Piece (2)"
    VINE_VALLEY_PUZZLE_PIECE_3 = "5-1 Vine Valley Puzzle Piece (3)"
    VINE_VALLEY_PUZZLE_PIECE_4 = "5-1 Vine Valley Puzzle Piece (4)"
    VINE_VALLEY_PUZZLE_PIECE_5 = "5-1 Vine Valley Puzzle Piece (5)"
    VINE_VALLEY_PUZZLE_PIECE_6 = "5-1 Vine Valley Puzzle Piece (6)"
    VINE_VALLEY_PUZZLE_PIECE_7 = "5-1 Vine Valley Puzzle Piece (7)"
    VINE_VALLEY_PUZZLE_PIECE_SET = "5-1 Vine Valley Puzzle Piece Set"
    VINE_VALLEY_KONG_LETTER_K = "5-1 Vine Valley Kong Letter (K)"
    VINE_VALLEY_KONG_LETTER_O = "5-1 Vine Valley Kong Letter (O)"
    VINE_VALLEY_KONG_LETTER_N = "5-1 Vine Valley Kong Letter (N)"
    VINE_VALLEY_KONG_LETTER_G = "5-1 Vine Valley Kong Letter (G)"
    VINE_VALLEY_KONG_LETTER_SET = "5-1 Vine Valley Kong Letter Set"
    VINE_VALLEY_CLEARED = "5-1 Vine Valley cleared"
    VINE_VALLEY_CLEARED_MIRROR = "5-1 Vine Valley cleared (Mirror)"
    VINE_VALLEY_CLEARED_TIME_TRIAL_BRONZE = "5-1 Vine Valley cleared (Time Trial) [Bronze]"
    VINE_VALLEY_CLEARED_TIME_TRIAL_SILVER = "5-1 Vine Valley cleared (Time Trial) [Silver]"
    VINE_VALLEY_CLEARED_TIME_TRIAL_GOLD = "5-1 Vine Valley cleared (Time Trial) [Gold]"

    CLINGY_SWINGY_PUZZLE_PIECE_1 = "5-2 Clingy_Swingy Puzzle Piece (1)"
    CLINGY_SWINGY_PUZZLE_PIECE_2 = "5-2 Clingy_Swingy Puzzle Piece (2)"
    CLINGY_SWINGY_PUZZLE_PIECE_3 = "5-2 Clingy_Swingy Puzzle Piece (3)"
    CLINGY_SWINGY_PUZZLE_PIECE_4 = "5-2 Clingy_Swingy Puzzle Piece (4)"
    CLINGY_SWINGY_PUZZLE_PIECE_5 = "5-2 Clingy_Swingy Puzzle Piece (5)"
    CLINGY_SWINGY_PUZZLE_PIECE_SET = "5-2 Clingy_Swingy Puzzle Piece Set"
    CLINGY_SWINGY_KONG_LETTER_K = "5-2 Clingy_Swingy Kong Letter (K)"
    CLINGY_SWINGY_KONG_LETTER_O = "5-2 Clingy_Swingy Kong Letter (O)"
    CLINGY_SWINGY_KONG_LETTER_N = "5-2 Clingy_Swingy Kong Letter (N)"
    CLINGY_SWINGY_KONG_LETTER_G = "5-2 Clingy_Swingy Kong Letter (G)"
    CLINGY_SWINGY_KONG_LETTER_SET = "5-2 Clingy_Swingy Kong Letter Set"
    CLINGY_SWINGY_CLEARED = "5-2 Clingy_Swingy cleared"
    CLINGY_SWINGY_CLEARED_MIRROR = "5-2 Clingy_Swingy cleared (Mirror)"
    CLINGY_SWINGY_CLEARED_TIME_TRIAL_BRONZE = "5-2 Clingy_Swingy cleared (Time Trial) [Bronze]"
    CLINGY_SWINGY_CLEARED_TIME_TRIAL_SILVER = "5-2 Clingy_Swingy cleared (Time Trial) [Silver]"
    CLINGY_SWINGY_CLEARED_TIME_TRIAL_GOLD = "5-2 Clingy_Swingy cleared (Time Trial) [Gold]"

    FLUTTER_FLYAWAY_PUZZLE_PIECE_1 = "5-3 Flutter Flyaway Puzzle Piece (1)"
    FLUTTER_FLYAWAY_PUZZLE_PIECE_2 = "5-3 Flutter Flyaway Puzzle Piece (2)"
    FLUTTER_FLYAWAY_PUZZLE_PIECE_3 = "5-3 Flutter Flyaway Puzzle Piece (3)"
    FLUTTER_FLYAWAY_PUZZLE_PIECE_4 = "5-3 Flutter Flyaway Puzzle Piece (4)"
    FLUTTER_FLYAWAY_PUZZLE_PIECE_5 = "5-3 Flutter Flyaway Puzzle Piece (5)"
    FLUTTER_FLYAWAY_PUZZLE_PIECE_6 = "5-3 Flutter Flyaway Puzzle Piece (6)"
    FLUTTER_FLYAWAY_PUZZLE_PIECE_7 = "5-3 Flutter Flyaway Puzzle Piece (7)"
    FLUTTER_FLYAWAY_PUZZLE_PIECE_SET = "5-3 Flutter Flyaway Puzzle Piece Set"
    FLUTTER_FLYAWAY_KONG_LETTER_K = "5-3 Flutter Flyaway Kong Letter (K)"
    FLUTTER_FLYAWAY_KONG_LETTER_O = "5-3 Flutter Flyaway Kong Letter (O)"
    FLUTTER_FLYAWAY_KONG_LETTER_N = "5-3 Flutter Flyaway Kong Letter (N)"
    FLUTTER_FLYAWAY_KONG_LETTER_G = "5-3 Flutter Flyaway Kong Letter (G)"
    FLUTTER_FLYAWAY_KONG_LETTER_SET = "5-3 Flutter Flyaway Kong Letter Set"
    FLUTTER_FLYAWAY_CLEARED = "5-3 Flutter Flyaway cleared"
    FLUTTER_FLYAWAY_CLEARED_MIRROR = "5-3 Flutter Flyaway cleared (Mirror)"
    FLUTTER_FLYAWAY_CLEARED_TIME_TRIAL_BRONZE = "5-3 Flutter Flyaway cleared (Time Trial) [Bronze]"
    FLUTTER_FLYAWAY_CLEARED_TIME_TRIAL_SILVER = "5-3 Flutter Flyaway cleared (Time Trial) [Silver]"
    FLUTTER_FLYAWAY_CLEARED_TIME_TRIAL_GOLD = "5-3 Flutter Flyaway cleared (Time Trial) [Gold]"

    TIPPIN_TOTEMS_PUZZLE_PIECE_1 = "5-4 Tippin' Totems Puzzle Piece (1)"
    TIPPIN_TOTEMS_PUZZLE_PIECE_2 = "5-4 Tippin' Totems Puzzle Piece (2)"
    TIPPIN_TOTEMS_PUZZLE_PIECE_3 = "5-4 Tippin' Totems Puzzle Piece (3)"
    TIPPIN_TOTEMS_PUZZLE_PIECE_4 = "5-4 Tippin' Totems Puzzle Piece (4)"
    TIPPIN_TOTEMS_PUZZLE_PIECE_5 = "5-4 Tippin' Totems Puzzle Piece (5)"
    TIPPIN_TOTEMS_PUZZLE_PIECE_6 = "5-4 Tippin' Totems Puzzle Piece (6)"
    TIPPIN_TOTEMS_PUZZLE_PIECE_7 = "5-4 Tippin' Totems Puzzle Piece (7)"
    TIPPIN_TOTEMS_PUZZLE_PIECE_SET = "5-4 Tippin' Totems Puzzle Piece Set"
    TIPPIN_TOTEMS_KONG_LETTER_K = "5-4 Tippin' Totems Kong Letter (K)"
    TIPPIN_TOTEMS_KONG_LETTER_O = "5-4 Tippin' Totems Kong Letter (O)"
    TIPPIN_TOTEMS_KONG_LETTER_N = "5-4 Tippin' Totems Kong Letter (N)"
    TIPPIN_TOTEMS_KONG_LETTER_G = "5-4 Tippin' Totems Kong Letter (G)"
    TIPPIN_TOTEMS_KONG_LETTER_SET = "5-4 Tippin' Totems Kong Letter Set"
    TIPPIN_TOTEMS_CLEARED = "5-4 Tippin' Totems cleared"
    TIPPIN_TOTEMS_CLEARED_MIRROR = "5-4 Tippin' Totems cleared (Mirror)"
    TIPPIN_TOTEMS_CLEARED_TIME_TRIAL_BRONZE = "5-4 Tippin' Totems cleared (Time Trial) [Bronze]"
    TIPPIN_TOTEMS_CLEARED_TIME_TRIAL_SILVER = "5-4 Tippin' Totems cleared (Time Trial) [Silver]"
    TIPPIN_TOTEMS_CLEARED_TIME_TRIAL_GOLD = "5-4 Tippin' Totems cleared (Time Trial) [Gold]"

    LONGSHOT_LAUNCH_PUZZLE_PIECE_1 = "5-5 Longshot Launch Puzzle Piece (1)"
    LONGSHOT_LAUNCH_PUZZLE_PIECE_2 = "5-5 Longshot Launch Puzzle Piece (2)"
    LONGSHOT_LAUNCH_PUZZLE_PIECE_3 = "5-5 Longshot Launch Puzzle Piece (3)"
    LONGSHOT_LAUNCH_PUZZLE_PIECE_4 = "5-5 Longshot Launch Puzzle Piece (4)"
    LONGSHOT_LAUNCH_PUZZLE_PIECE_5 = "5-5 Longshot Launch Puzzle Piece (5)"
    LONGSHOT_LAUNCH_PUZZLE_PIECE_6 = "5-5 Longshot Launch Puzzle Piece (6)"
    LONGSHOT_LAUNCH_PUZZLE_PIECE_7 = "5-5 Longshot Launch Puzzle Piece (7)"
    LONGSHOT_LAUNCH_PUZZLE_PIECE_SET = "5-5 Longshot Launch Puzzle Piece Set"
    LONGSHOT_LAUNCH_KONG_LETTER_K = "5-5 Longshot Launch Kong Letter (K)"
    LONGSHOT_LAUNCH_KONG_LETTER_O = "5-5 Longshot Launch Kong Letter (O)"
    LONGSHOT_LAUNCH_KONG_LETTER_N = "5-5 Longshot Launch Kong Letter (N)"
    LONGSHOT_LAUNCH_KONG_LETTER_G = "5-5 Longshot Launch Kong Letter (G)"
    LONGSHOT_LAUNCH_KONG_LETTER_SET = "5-5 Longshot Launch Kong Letter Set"
    LONGSHOT_LAUNCH_CLEARED = "5-5 Longshot Launch cleared"
    LONGSHOT_LAUNCH_CLEARED_MIRROR = "5-5 Longshot Launch cleared (Mirror)"
    LONGSHOT_LAUNCH_CLEARED_TIME_TRIAL_BRONZE = "5-5 Longshot Launch cleared (Time Trial) [Bronze]"
    LONGSHOT_LAUNCH_CLEARED_TIME_TRIAL_SILVER = "5-5 Longshot Launch cleared (Time Trial) [Silver]"
    LONGSHOT_LAUNCH_CLEARED_TIME_TRIAL_GOLD = "5-5 Longshot Launch cleared (Time Trial) [Gold]"

    SPRINGY_SPORES_PUZZLE_PIECE_1 = "5-6 Springy Spores Puzzle Piece (1)"
    SPRINGY_SPORES_PUZZLE_PIECE_2 = "5-6 Springy Spores Puzzle Piece (2)"
    SPRINGY_SPORES_PUZZLE_PIECE_3 = "5-6 Springy Spores Puzzle Piece (3)"
    SPRINGY_SPORES_PUZZLE_PIECE_4 = "5-6 Springy Spores Puzzle Piece (4)"
    SPRINGY_SPORES_PUZZLE_PIECE_5 = "5-6 Springy Spores Puzzle Piece (5)"
    SPRINGY_SPORES_PUZZLE_PIECE_6 = "5-6 Springy Spores Puzzle Piece (6)"
    SPRINGY_SPORES_PUZZLE_PIECE_7 = "5-6 Springy Spores Puzzle Piece (7)"
    SPRINGY_SPORES_PUZZLE_PIECE_SET = "5-6 Springy Spores Puzzle Piece Set"
    SPRINGY_SPORES_KONG_LETTER_K = "5-6 Springy Spores Kong Letter (K)"
    SPRINGY_SPORES_KONG_LETTER_O = "5-6 Springy Spores Kong Letter (O)"
    SPRINGY_SPORES_KONG_LETTER_N = "5-6 Springy Spores Kong Letter (N)"
    SPRINGY_SPORES_KONG_LETTER_G = "5-6 Springy Spores Kong Letter (G)"
    SPRINGY_SPORES_KONG_LETTER_SET = "5-6 Springy Spores Kong Letter Set"
    SPRINGY_SPORES_CLEARED = "5-6 Springy Spores cleared"
    SPRINGY_SPORES_CLEARED_MIRROR = "5-6 Springy Spores cleared (Mirror)"
    SPRINGY_SPORES_CLEARED_TIME_TRIAL_BRONZE = "5-6 Springy Spores cleared (Time Trial) [Bronze]"
    SPRINGY_SPORES_CLEARED_TIME_TRIAL_SILVER = "5-6 Springy Spores cleared (Time Trial) [Silver]"
    SPRINGY_SPORES_CLEARED_TIME_TRIAL_GOLD = "5-6 Springy Spores cleared (Time Trial) [Gold]"

    WIGGLEVINE_WONDERS_PUZZLE_PIECE_1 = "5-7 Wigglevine Wonders Puzzle Piece (1)"
    WIGGLEVINE_WONDERS_PUZZLE_PIECE_2 = "5-7 Wigglevine Wonders Puzzle Piece (2)"
    WIGGLEVINE_WONDERS_PUZZLE_PIECE_3 = "5-7 Wigglevine Wonders Puzzle Piece (3)"
    WIGGLEVINE_WONDERS_PUZZLE_PIECE_4 = "5-7 Wigglevine Wonders Puzzle Piece (4)"
    WIGGLEVINE_WONDERS_PUZZLE_PIECE_5 = "5-7 Wigglevine Wonders Puzzle Piece (5)"
    WIGGLEVINE_WONDERS_PUZZLE_PIECE_6 = "5-7 Wigglevine Wonders Puzzle Piece (6)"
    WIGGLEVINE_WONDERS_PUZZLE_PIECE_7 = "5-7 Wigglevine Wonders Puzzle Piece (7)"
    WIGGLEVINE_WONDERS_PUZZLE_PIECE_SET = "5-7 Wigglevine Wonders Puzzle Piece Set"
    WIGGLEVINE_WONDERS_KONG_LETTER_K = "5-7 Wigglevine Wonders Kong Letter (K)"
    WIGGLEVINE_WONDERS_KONG_LETTER_O = "5-7 Wigglevine Wonders Kong Letter (O)"
    WIGGLEVINE_WONDERS_KONG_LETTER_N = "5-7 Wigglevine Wonders Kong Letter (N)"
    WIGGLEVINE_WONDERS_KONG_LETTER_G = "5-7 Wigglevine Wonders Kong Letter (G)"
    WIGGLEVINE_WONDERS_KONG_LETTER_SET = "5-7 Wigglevine Wonders Kong Letter Set"
    WIGGLEVINE_WONDERS_CLEARED = "5-7 Wigglevine Wonders cleared"
    WIGGLEVINE_WONDERS_CLEARED_MIRROR = "5-7 Wigglevine Wonders cleared (Mirror)"
    WIGGLEVINE_WONDERS_CLEARED_TIME_TRIAL_BRONZE = "5-7 Wigglevine Wonders cleared (Time Trial) [Bronze]"
    WIGGLEVINE_WONDERS_CLEARED_TIME_TRIAL_SILVER = "5-7 Wigglevine Wonders cleared (Time Trial) [Silver]"
    WIGGLEVINE_WONDERS_CLEARED_TIME_TRIAL_GOLD = "5-7 Wigglevine Wonders cleared (Time Trial) [Gold]"

    MUNCHER_MARATHON_PUZZLE_PIECE_1 = "5-8 Muncher Marathon Puzzle Piece (1)"
    MUNCHER_MARATHON_PUZZLE_PIECE_2 = "5-8 Muncher Marathon Puzzle Piece (2)"
    MUNCHER_MARATHON_PUZZLE_PIECE_3 = "5-8 Muncher Marathon Puzzle Piece (3)"
    MUNCHER_MARATHON_PUZZLE_PIECE_4 = "5-8 Muncher Marathon Puzzle Piece (4)"
    MUNCHER_MARATHON_PUZZLE_PIECE_5 = "5-8 Muncher Marathon Puzzle Piece (5)"
    MUNCHER_MARATHON_PUZZLE_PIECE_SET = "5-8 Muncher Marathon Puzzle Piece Set"
    MUNCHER_MARATHON_KONG_LETTER_K = "5-8 Muncher Marathon Kong Letter (K)"
    MUNCHER_MARATHON_KONG_LETTER_O = "5-8 Muncher Marathon Kong Letter (O)"
    MUNCHER_MARATHON_KONG_LETTER_N = "5-8 Muncher Marathon Kong Letter (N)"
    MUNCHER_MARATHON_KONG_LETTER_G = "5-8 Muncher Marathon Kong Letter (G)"
    MUNCHER_MARATHON_KONG_LETTER_SET = "5-8 Muncher Marathon Kong Letter Set"
    MUNCHER_MARATHON_CLEARED = "5-8 Muncher Marathon cleared"
    MUNCHER_MARATHON_CLEARED_MIRROR = "5-8 Muncher Marathon cleared (Mirror)"
    MUNCHER_MARATHON_CLEARED_TIME_TRIAL_BRONZE = "5-8 Muncher Marathon cleared (Time Trial) [Bronze]"
    MUNCHER_MARATHON_CLEARED_TIME_TRIAL_SILVER = "5-8 Muncher Marathon cleared (Time Trial) [Silver]"
    MUNCHER_MARATHON_CLEARED_TIME_TRIAL_GOLD = "5-8 Muncher Marathon cleared (Time Trial) [Gold]"

    MANGORUBY_RUN_CLEARED = "5-B Mangoruby Run cleared"
    MANGORUBY_RUN_CLEARED_MIRROR = "5-B Mangoruby Run cleared (Mirror)"
    MANGORUBY_RUN_CLEARED_TIME_TRIAL_BRONZE = "5-B Mangoruby Run cleared (Time Trial) [Bronze]"
    MANGORUBY_RUN_CLEARED_TIME_TRIAL_SILVER = "5-B Mangoruby Run cleared (Time Trial) [Silver]"
    MANGORUBY_RUN_CLEARED_TIME_TRIAL_GOLD = "5-B Mangoruby Run cleared (Time Trial) [Gold]"

    BLAST_N_BOUNCE_PUZZLE_PIECE_1 = "5-K Blast 'n' Bounce Puzzle Piece (1)"
    BLAST_N_BOUNCE_PUZZLE_PIECE_2 = "5-K Blast 'n' Bounce Puzzle Piece (2)"
    BLAST_N_BOUNCE_PUZZLE_PIECE_3 = "5-K Blast 'n' Bounce Puzzle Piece (3)"
    BLAST_N_BOUNCE_PUZZLE_PIECE_4 = "5-K Blast 'n' Bounce Puzzle Piece (4)"
    BLAST_N_BOUNCE_PUZZLE_PIECE_5 = "5-K Blast 'n' Bounce Puzzle Piece (5)"
    BLAST_N_BOUNCE_PUZZLE_PIECE_SET = "5-K Blast 'n' Bounce Puzzle Piece Set"
    BLAST_N_BOUNCE_CLEARED = "5-K Blast 'n' Bounce cleared"
    BLAST_N_BOUNCE_CLEARED_MIRROR = "5-K Blast 'n' Bounce cleared (Mirror)"
    BLAST_N_BOUNCE_CLEARED_TIME_TRIAL_BRONZE = "5-K Blast 'n' Bounce cleared (Time Trial) [Bronze]"
    BLAST_N_BOUNCE_CLEARED_TIME_TRIAL_SILVER = "5-K Blast 'n' Bounce cleared (Time Trial) [Silver]"
    BLAST_N_BOUNCE_CLEARED_TIME_TRIAL_GOLD = "5-K Blast 'n' Bounce cleared (Time Trial) [Gold]"

    CLIFF_PUZZLE_BUNDLE = "Cliff Puzzle Bundle"
    CLIFF_KONG_BUNDLE = "Cliff Kong Bundle"
    CLIFF_CLEARED = "Cliff cleared"
    CLIFF_CLEARED_MIRROR = "Cliff cleared (Mirror)"
    CLIFF_CLEARED_TIME_TRIAL_BRONZE = "Cliff cleared (Time Trial) [Bronze]"
    CLIFF_CLEARED_TIME_TRIAL_SILVER = "Cliff cleared (Time Trial) [Silver]"
    CLIFF_CLEARED_TIME_TRIAL_GOLD = "Cliff cleared (Time Trial) [Gold]"
    CLIFF_SHOP_KEY = "Cliff Shop Key"
    CLIFF_SHOP_BALLOONSX1 = "Cliff Shop Ballon x 1"
    CLIFF_SHOP_BALLOONSX3 = "Cliff Shop Ballon x 3"
    CLIFF_SHOP_BALLOONSX7 = "Cliff Shop Ballon x 7"

    STICKY_SITUATION_PUZZLE_PIECE_1 = "6-1 Sticky Situation Puzzle Piece (1)"
    STICKY_SITUATION_PUZZLE_PIECE_2 = "6-1 Sticky Situation Puzzle Piece (2)"
    STICKY_SITUATION_PUZZLE_PIECE_3 = "6-1 Sticky Situation Puzzle Piece (3)"
    STICKY_SITUATION_PUZZLE_PIECE_4 = "6-1 Sticky Situation Puzzle Piece (4)"
    STICKY_SITUATION_PUZZLE_PIECE_5 = "6-1 Sticky Situation Puzzle Piece (5)"
    STICKY_SITUATION_PUZZLE_PIECE_6 = "6-1 Sticky Situation Puzzle Piece (6)"
    STICKY_SITUATION_PUZZLE_PIECE_7 = "6-1 Sticky Situation Puzzle Piece (7)"
    STICKY_SITUATION_PUZZLE_PIECE_8 = "6-1 Sticky Situation Puzzle Piece (8)"
    STICKY_SITUATION_PUZZLE_PIECE_9 = "6-1 Sticky Situation Puzzle Piece (9)"
    STICKY_SITUATION_PUZZLE_PIECE_SET = "6-1 Sticky Situation Puzzle Piece Set"
    STICKY_SITUATION_KONG_LETTER_K = "6-1 Sticky Situation Kong Letter (K)"
    STICKY_SITUATION_KONG_LETTER_O = "6-1 Sticky Situation Kong Letter (O)"
    STICKY_SITUATION_KONG_LETTER_N = "6-1 Sticky Situation Kong Letter (N)"
    STICKY_SITUATION_KONG_LETTER_G = "6-1 Sticky Situation Kong Letter (G)"
    STICKY_SITUATION_KONG_LETTER_SET = "6-1 Sticky Situation Kong Letter Set"
    STICKY_SITUATION_CLEARED = "6-1 Sticky Situation cleared"
    STICKY_SITUATION_CLEARED_MIRROR = "6-1 Sticky Situation cleared (Mirror)"
    STICKY_SITUATION_CLEARED_TIME_TRIAL_BRONZE = "6-1 Sticky Situation cleared (Time Trial) [Bronze]"
    STICKY_SITUATION_CLEARED_TIME_TRIAL_SILVER = "6-1 Sticky Situation cleared (Time Trial) [Silver]"
    STICKY_SITUATION_CLEARED_TIME_TRIAL_GOLD = "6-1 Sticky Situation cleared (Time Trial) [Gold]"

    PREHISTORIC_PATH_PUZZLE_PIECE_1 = "6-2 Prehistoric Path Puzzle Piece (1)"
    PREHISTORIC_PATH_PUZZLE_PIECE_2 = "6-2 Prehistoric Path Puzzle Piece (2)"
    PREHISTORIC_PATH_PUZZLE_PIECE_3 = "6-2 Prehistoric Path Puzzle Piece (3)"
    PREHISTORIC_PATH_PUZZLE_PIECE_4 = "6-2 Prehistoric Path Puzzle Piece (4)"
    PREHISTORIC_PATH_PUZZLE_PIECE_5 = "6-2 Prehistoric Path Puzzle Piece (5)"
    PREHISTORIC_PATH_PUZZLE_PIECE_SET = "6-2 Prehistoric Path Puzzle Piece Set"
    PREHISTORIC_PATH_KONG_LETTER_K = "6-2 Prehistoric Path Kong Letter (K)"
    PREHISTORIC_PATH_KONG_LETTER_O = "6-2 Prehistoric Path Kong Letter (O)"
    PREHISTORIC_PATH_KONG_LETTER_N = "6-2 Prehistoric Path Kong Letter (N)"
    PREHISTORIC_PATH_KONG_LETTER_G = "6-2 Prehistoric Path Kong Letter (G)"
    PREHISTORIC_PATH_KONG_LETTER_SET = "6-2 Prehistoric Path Kong Letter Set"
    PREHISTORIC_PATH_CLEARED = "6-2 Prehistoric Path cleared"
    PREHISTORIC_PATH_CLEARED_MIRROR = "6-2 Prehistoric Path cleared (Mirror)"
    PREHISTORIC_PATH_CLEARED_TIME_TRIAL_BRONZE = "6-2 Prehistoric Path cleared (Time Trial) [Bronze]"
    PREHISTORIC_PATH_CLEARED_TIME_TRIAL_SILVER = "6-2 Prehistoric Path cleared (Time Trial) [Silver]"
    PREHISTORIC_PATH_CLEARED_TIME_TRIAL_GOLD = "6-2 Prehistoric Path cleared (Time Trial) [Gold]"

    WEIGHTY_WAY_PUZZLE_PIECE_1 = "6-3 Weighty Way Puzzle Piece (1)"
    WEIGHTY_WAY_PUZZLE_PIECE_2 = "6-3 Weighty Way Puzzle Piece (2)"
    WEIGHTY_WAY_PUZZLE_PIECE_3 = "6-3 Weighty Way Puzzle Piece (3)"
    WEIGHTY_WAY_PUZZLE_PIECE_4 = "6-3 Weighty Way Puzzle Piece (4)"
    WEIGHTY_WAY_PUZZLE_PIECE_5 = "6-3 Weighty Way Puzzle Piece (5)"
    WEIGHTY_WAY_PUZZLE_PIECE_SET = "6-3 Weighty Way Puzzle Piece Set"
    WEIGHTY_WAY_KONG_LETTER_K = "6-3 Weighty Way Kong Letter (K)"
    WEIGHTY_WAY_KONG_LETTER_O = "6-3 Weighty Way Kong Letter (O)"
    WEIGHTY_WAY_KONG_LETTER_N = "6-3 Weighty Way Kong Letter (N)"
    WEIGHTY_WAY_KONG_LETTER_G = "6-3 Weighty Way Kong Letter (G)"
    WEIGHTY_WAY_KONG_LETTER_SET = "6-3 Weighty Way Kong Letter Set"
    WEIGHTY_WAY_CLEARED = "6-3 Weighty Way cleared"
    WEIGHTY_WAY_CLEARED_MIRROR = "6-3 Weighty Way cleared (Mirror)"
    WEIGHTY_WAY_CLEARED_TIME_TRIAL_BRONZE = "6-3 Weighty Way cleared (Time Trial) [Bronze]"
    WEIGHTY_WAY_CLEARED_TIME_TRIAL_SILVER = "6-3 Weighty Way cleared (Time Trial) [Silver]"
    WEIGHTY_WAY_CLEARED_TIME_TRIAL_GOLD = "6-3 Weighty Way cleared (Time Trial) [Gold]"

    BOULDER_ROLLER_PUZZLE_PIECE_1 = "6-4 Boulder Roller Puzzle Piece (1)"
    BOULDER_ROLLER_PUZZLE_PIECE_2 = "6-4 Boulder Roller Puzzle Piece (2)"
    BOULDER_ROLLER_PUZZLE_PIECE_3 = "6-4 Boulder Roller Puzzle Piece (3)"
    BOULDER_ROLLER_PUZZLE_PIECE_4 = "6-4 Boulder Roller Puzzle Piece (4)"
    BOULDER_ROLLER_PUZZLE_PIECE_5 = "6-4 Boulder Roller Puzzle Piece (5)"
    BOULDER_ROLLER_PUZZLE_PIECE_6 = "6-4 Boulder Roller Puzzle Piece (6)"
    BOULDER_ROLLER_PUZZLE_PIECE_7 = "6-4 Boulder Roller Puzzle Piece (7)"
    BOULDER_ROLLER_PUZZLE_PIECE_SET = "6-4 Boulder Roller Puzzle Piece Set"
    BOULDER_ROLLER_KONG_LETTER_K = "6-4 Boulder Roller Kong Letter (K)"
    BOULDER_ROLLER_KONG_LETTER_O = "6-4 Boulder Roller Kong Letter (O)"
    BOULDER_ROLLER_KONG_LETTER_N = "6-4 Boulder Roller Kong Letter (N)"
    BOULDER_ROLLER_KONG_LETTER_G = "6-4 Boulder Roller Kong Letter (G)"
    BOULDER_ROLLER_KONG_LETTER_SET = "6-4 Boulder Roller Kong Letter Set"
    BOULDER_ROLLER_CLEARED = "6-4 Boulder Roller cleared"
    BOULDER_ROLLER_CLEARED_MIRROR = "6-4 Boulder Roller cleared (Mirror)"
    BOULDER_ROLLER_CLEARED_TIME_TRIAL_BRONZE = "6-4 Boulder Roller cleared (Time Trial) [Bronze]"
    BOULDER_ROLLER_CLEARED_TIME_TRIAL_SILVER = "6-4 Boulder Roller cleared (Time Trial) [Silver]"
    BOULDER_ROLLER_CLEARED_TIME_TRIAL_GOLD = "6-4 Boulder Roller cleared (Time Trial) [Gold]"

    PRECARIOUS_PLATEAU_PUZZLE_PIECE_1 = "6-5 Precarious Plateau Puzzle Piece (1)"
    PRECARIOUS_PLATEAU_PUZZLE_PIECE_2 = "6-5 Precarious Plateau Puzzle Piece (2)"
    PRECARIOUS_PLATEAU_PUZZLE_PIECE_3 = "6-5 Precarious Plateau Puzzle Piece (3)"
    PRECARIOUS_PLATEAU_PUZZLE_PIECE_4 = "6-5 Precarious Plateau Puzzle Piece (4)"
    PRECARIOUS_PLATEAU_PUZZLE_PIECE_5 = "6-5 Precarious Plateau Puzzle Piece (5)"
    PRECARIOUS_PLATEAU_PUZZLE_PIECE_SET = "6-5 Precarious Plateau Puzzle Piece Set"
    PRECARIOUS_PLATEAU_KONG_LETTER_K = "6-5 Precarious Plateau Kong Letter (K)"
    PRECARIOUS_PLATEAU_KONG_LETTER_O = "6-5 Precarious Plateau Kong Letter (O)"
    PRECARIOUS_PLATEAU_KONG_LETTER_N = "6-5 Precarious Plateau Kong Letter (N)"
    PRECARIOUS_PLATEAU_KONG_LETTER_G = "6-5 Precarious Plateau Kong Letter (G)"
    PRECARIOUS_PLATEAU_KONG_LETTER_SET = "6-5 Precarious Plateau Kong Letter Set"
    PRECARIOUS_PLATEAU_CLEARED = "6-5 Precarious_Plateau cleared"
    PRECARIOUS_PLATEAU_CLEARED_MIRROR = "6-5 Precarious Plateau cleared (Mirror)"
    PRECARIOUS_PLATEAU_CLEARED_TIME_TRIAL_BRONZE = "6-5 Precarious Plateau cleared (Time Trial) [Bronze]"
    PRECARIOUS_PLATEAU_CLEARED_TIME_TRIAL_SILVER = "6-5 Precarious Plateau cleared (Time Trial) [Silver]"
    PRECARIOUS_PLATEAU_CLEARED_TIME_TRIAL_GOLD = "6-5 Precarious Plateau cleared (Time Trial) [Gold]"

    CRUMBLE_CANYON_PUZZLE_PIECE_1 = "6-6 Crumble Canyon Puzzle Piece (1)"
    CRUMBLE_CANYON_PUZZLE_PIECE_2 = "6-6 Crumble Canyon Puzzle Piece (2)"
    CRUMBLE_CANYON_PUZZLE_PIECE_3 = "6-6 Crumble Canyon Puzzle Piece (3)"
    CRUMBLE_CANYON_PUZZLE_PIECE_4 = "6-6 Crumble Canyon Puzzle Piece (4)"
    CRUMBLE_CANYON_PUZZLE_PIECE_5 = "6-6 Crumble Canyon Puzzle Piece (5)"
    CRUMBLE_CANYON_PUZZLE_PIECE_6 = "6-6 Crumble Canyon Puzzle Piece (6)"
    CRUMBLE_CANYON_PUZZLE_PIECE_7 = "6-6 Crumble Canyon Puzzle Piece (7)"
    CRUMBLE_CANYON_PUZZLE_PIECE_8 = "6-6 Crumble Canyon Puzzle Piece (8)"
    CRUMBLE_CANYON_PUZZLE_PIECE_9 = "6-6 Crumble Canyon Puzzle Piece (9)"
    CRUMBLE_CANYON_PUZZLE_PIECE_SET = "6-6 Crumble Canyon Puzzle Piece Set"
    CRUMBLE_CANYON_KONG_LETTER_K = "6-6 Crumble Canyon Kong Letter (K)"
    CRUMBLE_CANYON_KONG_LETTER_O = "6-6 Crumble Canyon Kong Letter (O)"
    CRUMBLE_CANYON_KONG_LETTER_N = "6-6 Crumble Canyon Kong Letter (N)"
    CRUMBLE_CANYON_KONG_LETTER_G = "6-6 Crumble Canyon Kong Letter (G)"
    CRUMBLE_CANYON_KONG_LETTER_SET = "6-6 Crumble Canyon Kong Letter Set"
    CRUMBLE_CANYON_CLEARED = "6-6 Crumble_Canyon cleared"
    CRUMBLE_CANYON_CLEARED_MIRROR = "6-6 Crumble Canyon cleared (Mirror)"
    CRUMBLE_CANYON_CLEARED_TIME_TRIAL_BRONZE = "6-6 Crumble Canyon cleared (Time Trial) [Bronze]"
    CRUMBLE_CANYON_CLEARED_TIME_TRIAL_SILVER = "6-6 Crumble Canyon cleared (Time Trial) [Silver]"
    CRUMBLE_CANYON_CLEARED_TIME_TRIAL_GOLD = "6-6 Crumble Canyon cleared (Time Trial) [Gold]"

    TIPPY_SHIPPY_PUZZLE_PIECE_1 = "6-7 Tippy Shippy Puzzle Piece (1)"
    TIPPY_SHIPPY_PUZZLE_PIECE_2 = "6-7 Tippy Shippy Puzzle Piece (2)"
    TIPPY_SHIPPY_PUZZLE_PIECE_3 = "6-7 Tippy Shippy Puzzle Piece (3)"
    TIPPY_SHIPPY_PUZZLE_PIECE_4 = "6-7 Tippy Shippy Puzzle Piece (4)"
    TIPPY_SHIPPY_PUZZLE_PIECE_5 = "6-7 Tippy Shippy Puzzle Piece (5)"
    TIPPY_SHIPPY_PUZZLE_PIECE_SET = "6-7 Tippy Shippy Puzzle Piece Set"
    TIPPY_SHIPPY_KONG_LETTER_K = "6-7 Tippy Shippy Kong Letter (K)"
    TIPPY_SHIPPY_KONG_LETTER_O = "6-7 Tippy Shippy Kong Letter (O)"
    TIPPY_SHIPPY_KONG_LETTER_N = "6-7 Tippy Shippy Kong Letter (N)"
    TIPPY_SHIPPY_KONG_LETTER_G = "6-7 Tippy Shippy Kong Letter (G)"
    TIPPY_SHIPPY_KONG_LETTER_SET = "6-7 Tippy Shippy Kong Letter Set"
    TIPPY_SHIPPY_CLEARED = "6-7 Tippy Shippy cleared"
    TIPPY_SHIPPY_CLEARED_MIRROR = "6-7 Tippy Shippy cleared (Mirror)"
    TIPPY_SHIPPY_CLEARED_TIME_TRIAL_BRONZE = "6-7 Tippy Shippy cleared (Time Trial) [Bronze]"
    TIPPY_SHIPPY_CLEARED_TIME_TRIAL_SILVER = "6-7 Tippy Shippy cleared (Time Trial) [Silver]"
    TIPPY_SHIPPY_CLEARED_TIME_TRIAL_GOLD = "6-7 Tippy Shippy cleared (Time Trial) [Gold]"

    CLIFFTOP_CLIMB_PUZZLE_PIECE_1 = "6-8 Clifftop Climb Puzzle Piece (1)"
    CLIFFTOP_CLIMB_PUZZLE_PIECE_2 = "6-8 Clifftop Climb Puzzle Piece (2)"
    CLIFFTOP_CLIMB_PUZZLE_PIECE_3 = "6-8 Clifftop Climb Puzzle Piece (3)"
    CLIFFTOP_CLIMB_PUZZLE_PIECE_4 = "6-8 Clifftop Climb Puzzle Piece (4)"
    CLIFFTOP_CLIMB_PUZZLE_PIECE_5 = "6-8 Clifftop Climb Puzzle Piece (5)"
    CLIFFTOP_CLIMB_PUZZLE_PIECE_SET = "6-8 Clifftop Climb Puzzle Piece Set"
    CLIFFTOP_CLIMB_KONG_LETTER_K = "6-8 Clifftop Climb Kong Letter (K)"
    CLIFFTOP_CLIMB_KONG_LETTER_O = "6-8 Clifftop Climb Kong Letter (O)"
    CLIFFTOP_CLIMB_KONG_LETTER_N = "6-8 Clifftop Climb Kong Letter (N)"
    CLIFFTOP_CLIMB_KONG_LETTER_G = "6-8 Clifftop Climb Kong Letter (G)"
    CLIFFTOP_CLIMB_KONG_LETTER_SET = "6-8 Clifftop Climb Kong Letter Set"
    CLIFFTOP_CLIMB_CLEARED = "6-8 Clifftop Climb cleared"
    CLIFFTOP_CLIMB_CLEARED_MIRROR = "6-8 Clifftop Climb cleared (Mirror)"
    CLIFFTOP_CLIMB_CLEARED_TIME_TRIAL_BRONZE = "6-8 Clifftop Climb cleared (Time Trial) [Bronze]"
    CLIFFTOP_CLIMB_CLEARED_TIME_TRIAL_SILVER = "6-8 Clifftop Climb cleared (Time Trial) [Silver]"
    CLIFFTOP_CLIMB_CLEARED_TIME_TRIAL_GOLD = "6-8 Clifftop Climb cleared (Time Trial) [Gold]"

    THUGLYS_HIGHRISE_CLEARED_MIRROR = "6-B Thugly's Highrise cleared (Mirror)"
    THUGLYS_HIGHRISE_CLEARED = "6-B Thugly's Highrise cleared"
    THUGLYS_HIGHRISE_CLEARED_TIME_TRIAL_BRONZE = "6-B Thugly's Highrise cleared (Time Trial) [Bronze]"
    THUGLYS_HIGHRISE_CLEARED_TIME_TRIAL_SILVER = "6-B Thugly's Highrise cleared (Time Trial) [Silver]"
    THUGLYS_HIGHRISE_CLEARED_TIME_TRIAL_GOLD = "6-B Thugly's Highrise cleared (Time Trial) [Gold]"

    PERILOUS_PASSAGE_PUZZLE_PIECE_1 = "6-K Perilous Passage Puzzle Piece (1)"
    PERILOUS_PASSAGE_PUZZLE_PIECE_2 = "6-K Perilous Passage Puzzle Piece (2)"
    PERILOUS_PASSAGE_PUZZLE_PIECE_3 = "6-K Perilous Passage Puzzle Piece (3)"
    PERILOUS_PASSAGE_PUZZLE_PIECE_4 = "6-K Perilous Passage Puzzle Piece (4)"
    PERILOUS_PASSAGE_PUZZLE_PIECE_5 = "6-K Perilous Passage Puzzle Piece (5)"
    PERILOUS_PASSAGE_PUZZLE_PIECE_SET = "6-K Perilous Passage Puzzle Piece Set"
    PERILOUS_PASSAGE_CLEARED = "6-K Perilous Passage cleared"
    PERILOUS_PASSAGE_CLEARED_MIRROR = "6-K Perilous Passage cleared (Mirror)"
    PERILOUS_PASSAGE_CLEARED_TIME_TRIAL_BRONZE = "6-K Perilous Passage cleared (Time Trial) [Bronze]"
    PERILOUS_PASSAGE_CLEARED_TIME_TRIAL_SILVER = "6-K Perilous Passage cleared (Time Trial) [Silver]"
    PERILOUS_PASSAGE_CLEARED_TIME_TRIAL_GOLD = "6-K Perilous Passage cleared (Time Trial) [Gold]"

    FACTORY_PUZZLE_BUNDLE = "Factory Puzzle Bundle"
    FACTORY_KONG_BUNDLE = "Factory Kong Bundle"
    FACTORY_CLEARED = "Factory cleared"
    FACTORY_CLEARED_MIRROR = "Factory cleared (Mirror)"
    FACTORY_CLEARED_TIME_TRIAL_BRONZE = "Factory cleared (Time Trial) [Bronze]"
    FACTORY_CLEARED_TIME_TRIAL_SILVER = "Factory cleared (Time Trial) [Silver]"
    FACTORY_CLEARED_TIME_TRIAL_GOLD = "Factory cleared (Time Trial) [Gold]"
    FACTORY_SHOP_KEY = "Factory Shop Key"
    FACTORY_SHOP_BALLOONSX1 = "Factory Shop Ballon x 1"
    FACTORY_SHOP_BALLOONSX3 = "Factory Shop Ballon x 3"
    FACTORY_SHOP_BALLOONSX7 = "Factory Shop Ballon x 7"

    FOGGY_FUMES_PUZZLE_PIECE_1 = "7-1 Foggy Fumes Puzzle Piece (1)"
    FOGGY_FUMES_PUZZLE_PIECE_2 = "7-1 Foggy Fumes Puzzle Piece (2)"
    FOGGY_FUMES_PUZZLE_PIECE_3 = "7-1 Foggy Fumes Puzzle Piece (3)"
    FOGGY_FUMES_PUZZLE_PIECE_4 = "7-1 Foggy Fumes Puzzle Piece (4)"
    FOGGY_FUMES_PUZZLE_PIECE_5 = "7-1 Foggy Fumes Puzzle Piece (5)"
    FOGGY_FUMES_PUZZLE_PIECE_6 = "7-1 Foggy Fumes Puzzle Piece (6)"
    FOGGY_FUMES_PUZZLE_PIECE_7 = "7-1 Foggy Fumes Puzzle Piece (7)"
    FOGGY_FUMES_PUZZLE_PIECE_SET = "7-1 Foggy Fumes Puzzle Piece Set"
    FOGGY_FUMES_KONG_LETTER_K = "7-1 Foggy Fumes Kong Letter (K)"
    FOGGY_FUMES_KONG_LETTER_O = "7-1 Foggy Fumes Kong Letter (O)"
    FOGGY_FUMES_KONG_LETTER_N = "7-1 Foggy Fumes Kong Letter (N)"
    FOGGY_FUMES_KONG_LETTER_G = "7-1 Foggy Fumes Kong Letter (G)"
    FOGGY_FUMES_KONG_LETTER_SET = "7-1 Foggy Fumes Kong Letter Set"
    FOGGY_FUMES_CLEARED = "7-1 Foggy Fumes cleared"
    FOGGY_FUMES_CLEARED_MIRROR = "7-1 Foggy Fumes cleared (Mirror)"
    FOGGY_FUMES_CLEARED_TIME_TRIAL_BRONZE = "7-1 Foggy Fumes cleared (Time Trial) [Bronze]"
    FOGGY_FUMES_CLEARED_TIME_TRIAL_SILVER = "7-1 Foggy Fumes cleared (Time Trial) [Silver]"
    FOGGY_FUMES_CLEARED_TIME_TRIAL_GOLD = "7-1 Foggy Fumes cleared (Time Trial) [Gold]"

    SLAMMIN_STEEL_PUZZLE_PIECE_1 = "7-2 Slammin' Steel Puzzle Piece (1)"
    SLAMMIN_STEEL_PUZZLE_PIECE_2 = "7-2 Slammin' Steel Puzzle Piece (2)"
    SLAMMIN_STEEL_PUZZLE_PIECE_3 = "7-2 Slammin' Steel Puzzle Piece (3)"
    SLAMMIN_STEEL_PUZZLE_PIECE_4 = "7-2 Slammin' Steel Puzzle Piece (4)"
    SLAMMIN_STEEL_PUZZLE_PIECE_5 = "7-2 Slammin' Steel Puzzle Piece (5)"
    SLAMMIN_STEEL_PUZZLE_PIECE_SET = "7-2 Slammin' Steel Puzzle Piece Set"
    SLAMMIN_STEEL_KONG_LETTER_K = "7-2 Slammin' Steel Kong Letter (K)"
    SLAMMIN_STEEL_KONG_LETTER_O = "7-2 Slammin' Steel Kong Letter (O)"
    SLAMMIN_STEEL_KONG_LETTER_N = "7-2 Slammin' Steel Kong Letter (N)"
    SLAMMIN_STEEL_KONG_LETTER_G = "7-2 Slammin' Steel Kong Letter (G)"
    SLAMMIN_STEEL_KONG_LETTER_SET = "7-2 Slammin' Steel Kong Letter Set"
    SLAMMIN_STEEL_CLEARED = "7-2 Slammin' Steel cleared"
    SLAMMIN_STEEL_CLEARED_MIRROR = "7-2 Slammin' Steel cleared (Mirror)"
    SLAMMIN_STEEL_CLEARED_TIME_TRIAL_BRONZE = "7-2 Slammin' Steel cleared (Time Trial) [Bronze]"
    SLAMMIN_STEEL_CLEARED_TIME_TRIAL_SILVER = "7-2 Slammin' Steel cleared (Time Trial) [Silver]"
    SLAMMIN_STEEL_CLEARED_TIME_TRIAL_GOLD = "7-2 Slammin' Steel cleared (Time Trial) [Gold]"

    HANDY_HAZARDS_PUZZLE_PIECE_1 = "7-3 Handy Hazards Puzzle Piece (1)"
    HANDY_HAZARDS_PUZZLE_PIECE_2 = "7-3 Handy Hazards Puzzle Piece (2)"
    HANDY_HAZARDS_PUZZLE_PIECE_3 = "7-3 Handy Hazards Puzzle Piece (3)"
    HANDY_HAZARDS_PUZZLE_PIECE_4 = "7-3 Handy Hazards Puzzle Piece (4)"
    HANDY_HAZARDS_PUZZLE_PIECE_5 = "7-3 Handy Hazards Puzzle Piece (5)"
    HANDY_HAZARDS_PUZZLE_PIECE_6 = "7-3 Handy Hazards Puzzle Piece (6)"
    HANDY_HAZARDS_PUZZLE_PIECE_7 = "7-3 Handy Hazards Puzzle Piece (7)"
    HANDY_HAZARDS_PUZZLE_PIECE_SET = "7-3 Handy Hazards Puzzle Piece Set"
    HANDY_HAZARDS_KONG_LETTER_K = "7-3 Handy Hazards Kong Letter (K)"
    HANDY_HAZARDS_KONG_LETTER_O = "7-3 Handy Hazards Kong Letter (O)"
    HANDY_HAZARDS_KONG_LETTER_N = "7-3 Handy Hazards Kong Letter (N)"
    HANDY_HAZARDS_KONG_LETTER_G = "7-3 Handy Hazards Kong Letter (G)"
    HANDY_HAZARDS_KONG_LETTER_SET = "7-3 Handy Hazards Kong Letter Set"
    HANDY_HAZARDS_CLEARED = "7-3 Handy Hazards cleared"
    HANDY_HAZARDS_CLEARED_MIRROR = "7-3 Handy Hazards cleared (Mirror)"
    HANDY_HAZARDS_CLEARED_TIME_TRIAL_BRONZE = "7-3 Handy Hazards cleared (Time Trial) [Bronze]"
    HANDY_HAZARDS_CLEARED_TIME_TRIAL_SILVER = "7-3 Handy Hazards cleared (Time Trial) [Silver]"
    HANDY_HAZARDS_CLEARED_TIME_TRIAL_GOLD = "7-3 Handy Hazards cleared (Time Trial) [Gold]"

    GEAR_GETAWAY_PUZZLE_PIECE_1 = "7-4 Gear Getaway Puzzle Piece (1)"
    GEAR_GETAWAY_PUZZLE_PIECE_2 = "7-4 Gear Getaway Puzzle Piece (2)"
    GEAR_GETAWAY_PUZZLE_PIECE_3 = "7-4 Gear Getaway Puzzle Piece (3)"
    GEAR_GETAWAY_PUZZLE_PIECE_4 = "7-4 Gear Getaway Puzzle Piece (4)"
    GEAR_GETAWAY_PUZZLE_PIECE_5 = "7-4 Gear Getaway Puzzle Piece (5)"
    GEAR_GETAWAY_PUZZLE_PIECE_6 = "7-4 Gear Getaway Puzzle Piece (6)"
    GEAR_GETAWAY_PUZZLE_PIECE_7 = "7-4 Gear Getaway Puzzle Piece (7)"
    GEAR_GETAWAY_PUZZLE_PIECE_SET = "7-4 Gear Getaway Puzzle Piece Set"
    GEAR_GETAWAY_KONG_LETTER_K = "7-4 Gear Getaway Kong Letter (K)"
    GEAR_GETAWAY_KONG_LETTER_O = "7-4 Gear Getaway Kong Letter (O)"
    GEAR_GETAWAY_KONG_LETTER_N = "7-4 Gear Getaway Kong Letter (N)"
    GEAR_GETAWAY_KONG_LETTER_G = "7-4 Gear Getaway Kong Letter (G)"
    GEAR_GETAWAY_KONG_LETTER_SET = "7-4 Gear Getaway Kong Letter Set"
    GEAR_GETAWAY_CLEARED = "7-4 Gear Getaway cleared"
    GEAR_GETAWAY_CLEARED_MIRROR = "7-4 Gear Getaway cleared (Mirror)"
    GEAR_GETAWAY_CLEARED_TIME_TRIAL_BRONZE = "7-4 Gear Getaway cleared (Time Trial) [Bronze]"
    GEAR_GETAWAY_CLEARED_TIME_TRIAL_SILVER = "7-4 Gear Getaway cleared (Time Trial) [Silver]"
    GEAR_GETAWAY_CLEARED_TIME_TRIAL_GOLD = "7-4 Gear Getaway cleared (Time Trial) [Gold]"

    COG_JOG_PUZZLE_PIECE_1 = "7-5 Cog Jog Puzzle Piece (1)"
    COG_JOG_PUZZLE_PIECE_2 = "7-5 Cog Jog Puzzle Piece (2)"
    COG_JOG_PUZZLE_PIECE_3 = "7-5 Cog Jog Puzzle Piece (3)"
    COG_JOG_PUZZLE_PIECE_4 = "7-5 Cog Jog Puzzle Piece (4)"
    COG_JOG_PUZZLE_PIECE_5 = "7-5 Cog Jog Puzzle Piece (5)"
    COG_JOG_PUZZLE_PIECE_6 = "7-5 Cog Jog Puzzle Piece (6)"
    COG_JOG_PUZZLE_PIECE_7 = "7-5 Cog Jog Puzzle Piece (7)"
    COG_JOG_PUZZLE_PIECE_8 = "7-5 Cog Jog Puzzle Piece (8)"
    COG_JOG_PUZZLE_PIECE_9 = "7-5 Cog Jog Puzzle Piece (9)"
    COG_JOG_PUZZLE_PIECE_SET = "7-5 Cog Jog Puzzle Piece Set"
    COG_JOG_KONG_LETTER_K = "7-5 Cog Jog Kong Letter (K)"
    COG_JOG_KONG_LETTER_O = "7-5 Cog Jog Kong Letter (O)"
    COG_JOG_KONG_LETTER_N = "7-5 Cog Jog Kong Letter (N)"
    COG_JOG_KONG_LETTER_G = "7-5 Cog Jog Kong Letter (G)"
    COG_JOG_KONG_LETTER_SET = "7-5 Cog Jog Kong Letter Set"
    COG_JOG_CLEARED = "7-5 Cog Jog cleared"
    COG_JOG_CLEARED_MIRROR = "7-5 Cog Jog cleared (Mirror)"
    COG_JOG_CLEARED_TIME_TRIAL_BRONZE = "7-5 Cog Jog cleared (Time Trial) [Bronze]"
    COG_JOG_CLEARED_TIME_TRIAL_SILVER = "7-5 Cog Jog cleared (Time Trial) [Silver]"
    COG_JOG_CLEARED_TIME_TRIAL_GOLD = "7-5 Cog Jog cleared (Time Trial) [Gold]"

    SWITCHEROO_PUZZLE_PIECE_1 = "7-6 Switcheroo Puzzle Piece (1)"
    SWITCHEROO_PUZZLE_PIECE_2 = "7-6 Switcheroo Puzzle Piece (2)"
    SWITCHEROO_PUZZLE_PIECE_3 = "7-6 Switcheroo Puzzle Piece (3)"
    SWITCHEROO_PUZZLE_PIECE_4 = "7-6 Switcheroo Puzzle Piece (4)"
    SWITCHEROO_PUZZLE_PIECE_5 = "7-6 Switcheroo Puzzle Piece (5)"
    SWITCHEROO_PUZZLE_PIECE_SET = "7-6 Switcheroo Puzzle Piece Set"
    SWITCHEROO_KONG_LETTER_K = "7-6 Switcheroo Kong Letter (K)"
    SWITCHEROO_KONG_LETTER_O = "7-6 Switcheroo Kong Letter (O)"
    SWITCHEROO_KONG_LETTER_N = "7-6 Switcheroo Kong Letter (N)"
    SWITCHEROO_KONG_LETTER_G = "7-6 Switcheroo Kong Letter (G)"
    SWITCHEROO_KONG_LETTER_SET = "7-6 Switcheroo Kong Letter Set"
    SWITCHEROO_CLEARED = "7-6 Switcheroo cleared"
    SWITCHEROO_CLEARED_MIRROR = "7-6 Switcheroo cleared (Mirror)"
    SWITCHEROO_CLEARED_TIME_TRIAL_BRONZE = "7-6 Switcheroo cleared (Time Trial) [Bronze]"
    SWITCHEROO_CLEARED_TIME_TRIAL_SILVER = "7-6 Switcheroo cleared (Time Trial) [Silver]"
    SWITCHEROO_CLEARED_TIME_TRIAL_GOLD = "7-6 Switcheroo cleared (Time Trial) [Gold]"

    MUSIC_MADNESS_PUZZLE_PIECE_1 = "7-7 Music Madness Puzzle Piece (1)"
    MUSIC_MADNESS_PUZZLE_PIECE_2 = "7-7 Music Madness Puzzle Piece (2)"
    MUSIC_MADNESS_PUZZLE_PIECE_3 = "7-7 Music Madness Puzzle Piece (3)"
    MUSIC_MADNESS_PUZZLE_PIECE_4 = "7-7 Music Madness Puzzle Piece (4)"
    MUSIC_MADNESS_PUZZLE_PIECE_5 = "7-7 Music Madness Puzzle Piece (5)"
    MUSIC_MADNESS_PUZZLE_PIECE_SET = "7-7 Music Madness Puzzle Piece Set"
    MUSIC_MADNESS_KONG_LETTER_K = "7-7 Music Madness Kong Letter (K)"
    MUSIC_MADNESS_KONG_LETTER_O = "7-7 Music Madness Kong Letter (O)"
    MUSIC_MADNESS_KONG_LETTER_N = "7-7 Music Madness Kong Letter (N)"
    MUSIC_MADNESS_KONG_LETTER_G = "7-7 Music Madness Kong Letter (G)"
    MUSIC_MADNESS_KONG_LETTER_SET = "7-7 Music Madness Kong Letter Set"
    MUSIC_MADNESS_CLEARED = "7-7 Music Madness cleared"
    MUSIC_MADNESS_CLEARED_MIRROR = "7-7 Music Madness cleared (Mirror)"
    MUSIC_MADNESS_CLEARED_TIME_TRIAL_BRONZE = "7-7 Music Madness cleared (Time Trial) [Bronze]"
    MUSIC_MADNESS_CLEARED_TIME_TRIAL_SILVER = "7-7 Music Madness cleared (Time Trial) [Silver]"
    MUSIC_MADNESS_CLEARED_TIME_TRIAL_GOLD = "7-7 Music Madness cleared (Time Trial) [Gold]"

    LIFT_OFF_LAUNCH_CLEARED = "7-R Lift Off Launch cleared"

    FEATHER_FIEND_CLEARED = "7-B Feather Fiend cleared"
    FEATHER_FIEND_CLEARED_MIRROR = "7-B Feather Fiend cleared (Mirror)"
    FEATHER_FIEND_CLEARED_TIME_TRIAL_BRONZE = "7-B Feather Fiend cleared (Time Trial) [Bronze]"
    FEATHER_FIEND_CLEARED_TIME_TRIAL_SILVER = "7-B Feather Fiend cleared (Time Trial) [Silver]"
    FEATHER_FIEND_CLEARED_TIME_TRIAL_GOLD = "7-B Feather Fiend cleared (Time Trial) [Gold]"

    TREACHEROUS_TRACK_PUZZLE_PIECE_1 = "7-K Treacherous Track Puzzle Piece (1)"
    TREACHEROUS_TRACK_PUZZLE_PIECE_2 = "7-K Treacherous Track Puzzle Piece (2)"
    TREACHEROUS_TRACK_PUZZLE_PIECE_3 = "7-K Treacherous Track Puzzle Piece (3)"
    TREACHEROUS_TRACK_PUZZLE_PIECE_4 = "7-K Treacherous Track Puzzle Piece (4)"
    TREACHEROUS_TRACK_PUZZLE_PIECE_5 = "7-K Treacherous Track Puzzle Piece (5)"
    TREACHEROUS_TRACK_PUZZLE_PIECE_SET = "7-K Treacherous Track Puzzle Piece Set"
    TREACHEROUS_TRACK_CLEARED = "7-K Treacherous Track cleared"
    TREACHEROUS_TRACK_CLEARED_MIRROR = "7-K Treacherous Track cleared (Mirror)"
    TREACHEROUS_TRACK_CLEARED_TIME_TRIAL_BRONZE = "7-K Treacherous Track cleared (Time Trial) [Bronze]"
    TREACHEROUS_TRACK_CLEARED_TIME_TRIAL_SILVER = "7-K Treacherous Track cleared (Time Trial) [Silver]"
    TREACHEROUS_TRACK_CLEARED_TIME_TRIAL_GOLD = "7-K Treacherous Track cleared (Time Trial) [Gold]"

    VOLCANO_PUZZLE_BUNDLE = "Volcano Puzzle Bundle"
    VOLCANO_KONG_BUNDLE = "Volcano Kong Bundle"
    VOLCANO_CLEARED = "Volcano cleared"
    VOLCANO_CLEARED_MIRROR = "Volcano cleared (Mirror)"
    VOLCANO_CLEARED_TIME_TRIAL_BRONZE = "Volcano cleared (Time Trial) [Bronze]"
    VOLCANO_CLEARED_TIME_TRIAL_SILVER = "Volcano cleared (Time Trial) [Silver]"
    VOLCANO_CLEARED_TIME_TRIAL_GOLD = "Volcano cleared (Time Trial) [Gold]"
    VOLCANO_SHOP_KEY = "Volcano Shop Key"
    VOLCANO_SHOP_BALLOONSX1 = "Volcano Shop Ballon x 1"
    VOLCANO_SHOP_BALLOONSX3 = "Volcano Shop Ballon x 3"
    VOLCANO_SHOP_BALLOONSX7 = "Volcano Shop Ballon x 7"

    FURIOUS_FIRE_PUZZLE_PIECE_1 = "8-1 Furious Fire Puzzle Piece (1)"
    FURIOUS_FIRE_PUZZLE_PIECE_2 = "8-1 Furious Fire Puzzle Piece (2)"
    FURIOUS_FIRE_PUZZLE_PIECE_3 = "8-1 Furious Fire Puzzle Piece (3)"
    FURIOUS_FIRE_PUZZLE_PIECE_4 = "8-1 Furious Fire Puzzle Piece (4)"
    FURIOUS_FIRE_PUZZLE_PIECE_5 = "8-1 Furious Fire Puzzle Piece (5)"
    FURIOUS_FIRE_PUZZLE_PIECE_SET = "8-1 Furious Fire Puzzle Piece Set"
    FURIOUS_FIRE_KONG_LETTER_K = "8-1 Furious Fire Kong Letter (K)"
    FURIOUS_FIRE_KONG_LETTER_O = "8-1 Furious Fire Kong Letter (O)"
    FURIOUS_FIRE_KONG_LETTER_N = "8-1 Furious Fire Kong Letter (N)"
    FURIOUS_FIRE_KONG_LETTER_G = "8-1 Furious Fire Kong Letter (G)"
    FURIOUS_FIRE_KONG_LETTER_SET = "8-1 Furious Fire Kong Letter Set"
    FURIOUS_FIRE_CLEARED = "8-1 Furious Fire cleared"
    FURIOUS_FIRE_CLEARED_MIRROR = "8-1 Furious Fire cleared (Mirror)"
    FURIOUS_FIRE_CLEARED_TIME_TRIAL_BRONZE = "8-1 Furious Fire cleared (Time Trial) [Bronze]"
    FURIOUS_FIRE_CLEARED_TIME_TRIAL_SILVER = "8-1 Furious Fire cleared (Time Trial) [Silver]"
    FURIOUS_FIRE_CLEARED_TIME_TRIAL_GOLD = "8-1 Furious Fire cleared (Time Trial) [Gold]"

    HOT_ROCKET_PUZZLE_PIECE_1 = "8-2 Hot Rocket Puzzle Piece (1)"
    HOT_ROCKET_PUZZLE_PIECE_2 = "8-2 Hot Rocket Puzzle Piece (2)"
    HOT_ROCKET_PUZZLE_PIECE_3 = "8-2 Hot Rocket Puzzle Piece (3)"
    HOT_ROCKET_PUZZLE_PIECE_4 = "8-2 Hot Rocket Puzzle Piece (4)"
    HOT_ROCKET_PUZZLE_PIECE_5 = "8-2 Hot Rocket Puzzle Piece (5)"
    HOT_ROCKET_PUZZLE_PIECE_SET = "8-2 Hot Rocket Puzzle Piece Set"
    HOT_ROCKET_KONG_LETTER_K = "8-2 Hot Rocket Kong Letter (K)"
    HOT_ROCKET_KONG_LETTER_O = "8-2 Hot Rocket Kong Letter (O)"
    HOT_ROCKET_KONG_LETTER_N = "8-2 Hot Rocket Kong Letter (N)"
    HOT_ROCKET_KONG_LETTER_G = "8-2 Hot Rocket Kong Letter (G)"
    HOT_ROCKET_KONG_LETTER_SET = "8-2 Hot Rocket Kong Letter Set"
    HOT_ROCKET_CLEARED = "8-2 Hot Rocket cleared"
    HOT_ROCKET_CLEARED_MIRROR = "8-2 Hot Rocket cleared (Mirror)"
    HOT_ROCKET_CLEARED_TIME_TRIAL_BRONZE = "8-2 Hot Rocket cleared (Time Trial) [Bronze]"
    HOT_ROCKET_CLEARED_TIME_TRIAL_SILVER = "8-2 Hot Rocket cleared (Time Trial) [Silver]"
    HOT_ROCKET_CLEARED_TIME_TRIAL_GOLD = "8-2 Hot Rocket cleared (Time Trial) [Gold]"

    ROASTING_RAILS_PUZZLE_PIECE_1 = "8-3 Roasting Rails Puzzle Piece (1)"
    ROASTING_RAILS_PUZZLE_PIECE_2 = "8-3 Roasting Rails Puzzle Piece (2)"
    ROASTING_RAILS_PUZZLE_PIECE_3 = "8-3 Roasting Rails Puzzle Piece (3)"
    ROASTING_RAILS_PUZZLE_PIECE_4 = "8-3 Roasting Rails Puzzle Piece (4)"
    ROASTING_RAILS_PUZZLE_PIECE_5 = "8-3 Roasting Rails Puzzle Piece (5)"
    ROASTING_RAILS_PUZZLE_PIECE_SET = "8-3 Roasting Rails Puzzle Piece Set"
    ROASTING_RAILS_KONG_LETTER_K = "8-3 Roasting Rails Kong Letter (K)"
    ROASTING_RAILS_KONG_LETTER_O = "8-3 Roasting Rails Kong Letter (O)"
    ROASTING_RAILS_KONG_LETTER_N = "8-3 Roasting Rails Kong Letter (N)"
    ROASTING_RAILS_KONG_LETTER_G = "8-3 Roasting Rails Kong Letter (G)"
    ROASTING_RAILS_KONG_LETTER_SET = "8-3 Roasting Rails Kong Letter Set"
    ROASTING_RAILS_CLEARED = "8-3 Roasting Rails cleared"
    ROASTING_RAILS_CLEARED_MIRROR = "8-3 Roasting Rails cleared (Mirror)"
    ROASTING_RAILS_CLEARED_TIME_TRIAL_BRONZE = "8-3 Roasting Rails cleared (Time Trial) [Bronze]"
    ROASTING_RAILS_CLEARED_TIME_TRIAL_SILVER = "8-3 Roasting Rails cleared (Time Trial) [Silver]"
    ROASTING_RAILS_CLEARED_TIME_TRIAL_GOLD = "8-3 Roasting Rails cleared (Time Trial) [Gold]"

    SMOKEY_PEAK_PUZZLE_PIECE_1 = "8-4 Smokey Peak Puzzle Piece (1)"
    SMOKEY_PEAK_PUZZLE_PIECE_2 = "8-4 Smokey Peak Puzzle Piece (2)"
    SMOKEY_PEAK_PUZZLE_PIECE_3 = "8-4 Smokey Peak Puzzle Piece (3)"
    SMOKEY_PEAK_PUZZLE_PIECE_4 = "8-4 Smokey Peak Puzzle Piece (4)"
    SMOKEY_PEAK_PUZZLE_PIECE_5 = "8-4 Smokey Peak Puzzle Piece (5)"
    SMOKEY_PEAK_PUZZLE_PIECE_SET = "8-4 Smokey Peak Puzzle Piece Set"
    SMOKEY_PEAK_KONG_LETTER_K = "8-4 Smokey Peak Kong Letter (K)"
    SMOKEY_PEAK_KONG_LETTER_O = "8-4 Smokey Peak Kong Letter (O)"
    SMOKEY_PEAK_KONG_LETTER_N = "8-4 Smokey Peak Kong Letter (N)"
    SMOKEY_PEAK_KONG_LETTER_G = "8-4 Smokey Peak Kong Letter (G)"
    SMOKEY_PEAK_KONG_LETTER_SET = "8-4 Smokey Peak Kong Letter Set"
    SMOKEY_PEAK_CLEARED = "8-4 Smokey Peak cleared"
    SMOKEY_PEAK_CLEARED_MIRROR = "8-4 Smokey Peak cleared (Mirror)"
    SMOKEY_PEAK_CLEARED_TIME_TRIAL_BRONZE = "8-4 Smokey Peak cleared (Time Trial) [Bronze]"
    SMOKEY_PEAK_CLEARED_TIME_TRIAL_SILVER = "8-4 Smokey Peak cleared (Time Trial) [Silver]"
    SMOKEY_PEAK_CLEARED_TIME_TRIAL_GOLD = "8-4 Smokey Peak cleared (Time Trial) [Gold]"

    BOBBING_BASALT_PUZZLE_PIECE_1 = "8-5 Bobbing Basalt Puzzle Piece (1)"
    BOBBING_BASALT_PUZZLE_PIECE_2 = "8-5 Bobbing Basalt Puzzle Piece (2)"
    BOBBING_BASALT_PUZZLE_PIECE_3 = "8-5 Bobbing Basalt Puzzle Piece (3)"
    BOBBING_BASALT_PUZZLE_PIECE_4 = "8-5 Bobbing Basalt Puzzle Piece (4)"
    BOBBING_BASALT_PUZZLE_PIECE_5 = "8-5 Bobbing Basalt Puzzle Piece (5)"
    BOBBING_BASALT_PUZZLE_PIECE_6 = "8-5 Bobbing Basalt Puzzle Piece (6)"
    BOBBING_BASALT_PUZZLE_PIECE_7 = "8-5 Bobbing Basalt Puzzle Piece (7)"
    BOBBING_BASALT_PUZZLE_PIECE_SET = "8-5 Bobbing Basalt Puzzle Piece Set"
    BOBBING_BASALT_KONG_LETTER_K = "8-5 Bobbing Basalt Kong Letter (K)"
    BOBBING_BASALT_KONG_LETTER_O = "8-5 Bobbing Basalt Kong Letter (O)"
    BOBBING_BASALT_KONG_LETTER_N = "8-5 Bobbing Basalt Kong Letter (N)"
    BOBBING_BASALT_KONG_LETTER_G = "8-5 Bobbing Basalt Kong Letter (G)"
    BOBBING_BASALT_KONG_LETTER_SET = "8-5 Bobbing Basalt Kong Letter Set"
    BOBBING_BASALT_CLEARED = "8-5 Bobbing Basalt cleared"
    BOBBING_BASALT_CLEARED_MIRROR = "8-5 Bobbing Basalt cleared (Mirror)"
    BOBBING_BASALT_CLEARED_TIME_TRIAL_BRONZE = "8-5 Bobbing Basalt cleared (Time Trial) [Bronze]"
    BOBBING_BASALT_CLEARED_TIME_TRIAL_SILVER = "8-5 Bobbing Basalt cleared (Time Trial) [Silver]"
    BOBBING_BASALT_CLEARED_TIME_TRIAL_GOLD = "8-5 Bobbing Basalt cleared (Time Trial) [Gold]"

    MOVING_MELTERS_PUZZLE_PIECE_1 = "8-6 Moving Melters Puzzle Piece (1)"
    MOVING_MELTERS_PUZZLE_PIECE_2 = "8-6 Moving Melters Puzzle Piece (2)"
    MOVING_MELTERS_PUZZLE_PIECE_3 = "8-6 Moving Melters Puzzle Piece (3)"
    MOVING_MELTERS_PUZZLE_PIECE_4 = "8-6 Moving Melters Puzzle Piece (4)"
    MOVING_MELTERS_PUZZLE_PIECE_5 = "8-6 Moving Melters Puzzle Piece (5)"
    MOVING_MELTERS_PUZZLE_PIECE_SET = "8-6 Moving Melters Puzzle Piece Set"
    MOVING_MELTERS_KONG_LETTER_K = "8-6 Moving Melters Kong Letter (K)"
    MOVING_MELTERS_KONG_LETTER_O = "8-6 Moving Melters Kong Letter (O)"
    MOVING_MELTERS_KONG_LETTER_N = "8-6 Moving Melters Kong Letter (N)"
    MOVING_MELTERS_KONG_LETTER_G = "8-6 Moving Melters Kong Letter (G)"
    MOVING_MELTERS_KONG_LETTER_SET = "8-6 Moving Melters Kong Letter Set"
    MOVING_MELTERS_CLEARED = "8-6 Moving Melters cleared"
    MOVING_MELTERS_CLEARED_MIRROR = "8-6 Moving Melters cleared (Mirror)"
    MOVING_MELTERS_CLEARED_TIME_TRIAL_BRONZE = "8-6 Moving Melters cleared (Time Trial) [Bronze]"
    MOVING_MELTERS_CLEARED_TIME_TRIAL_SILVER = "8-6 Moving Melters cleared (Time Trial) [Silver]"
    MOVING_MELTERS_CLEARED_TIME_TRIAL_GOLD = "8-6 Moving Melters cleared (Time Trial) [Gold]"

    RED_RED_RISING_PUZZLE_PIECE_1 = "8-7 Red Red Rising Puzzle Piece (1)"
    RED_RED_RISING_PUZZLE_PIECE_2 = "8-7 Red Red Rising Puzzle Piece (2)"
    RED_RED_RISING_PUZZLE_PIECE_3 = "8-7 Red Red Rising Puzzle Piece (3)"
    RED_RED_RISING_PUZZLE_PIECE_4 = "8-7 Red Red Rising Puzzle Piece (4)"
    RED_RED_RISING_PUZZLE_PIECE_5 = "8-7 Red Red Rising Puzzle Piece (5)"
    RED_RED_RISING_PUZZLE_PIECE_SET = "8-7 Red Red Rising Puzzle Piece Set"
    RED_RED_RISING_KONG_LETTER_K = "8-7 Red Red Rising Kong Letter (K)"
    RED_RED_RISING_KONG_LETTER_O = "8-7 Red Red Rising Kong Letter (O)"
    RED_RED_RISING_KONG_LETTER_N = "8-7 Red Red Rising Kong Letter (N)"
    RED_RED_RISING_KONG_LETTER_G = "8-7 Red Red Rising Kong Letter (G)"
    RED_RED_RISING_KONG_LETTER_SET = "8-7 Red Red Rising Kong Letter Set"
    RED_RED_RISING_CLEARED = "8-7 Red Red Rising cleared"
    RED_RED_RISING_CLEARED_MIRROR = "8-7 Red Red Rising cleared (Mirror)"
    RED_RED_RISING_CLEARED_TIME_TRIAL_BRONZE = "8-7 Red Red Rising cleared (Time Trial) [Bronze]"
    RED_RED_RISING_CLEARED_TIME_TRIAL_SILVER = "8-7 Red Red Rising cleared (Time Trial) [Silver]"
    RED_RED_RISING_CLEARED_TIME_TRIAL_GOLD = "8-7 Red Red Rising cleared (Time Trial) [Gold]"

    TIKI_TONG_TERROR_CLEARED = "8-B Tiki Tong Terror cleared"
    TIKI_TONG_TERROR_CLEARED_MIRROR = "8-B Tiki Tong Terror cleared (Mirror)"
    TIKI_TONG_TERROR_CLEARED_TIME_TRIAL_BRONZE = "8-B Tiki Tong Terror cleared (Time Trial) [Bronze]"
    TIKI_TONG_TERROR_CLEARED_TIME_TRIAL_SILVER = "8-B Tiki Tong Terror cleared (Time Trial) [Silver]"
    TIKI_TONG_TERROR_CLEARED_TIME_TRIAL_GOLD = "8-B Tiki Tong Terror cleared (Time Trial) [Gold]"

    FIVE_MONKEY_TRIAL_PUZZLE_PIECE_1 = "8-K Five Monkey Trial Puzzle Piece (1)"
    FIVE_MONKEY_TRIAL_PUZZLE_PIECE_2 = "8-K Five Monkey Trial Puzzle Piece (2)"
    FIVE_MONKEY_TRIAL_PUZZLE_PIECE_3 = "8-K Five Monkey Trial Puzzle Piece (3)"
    FIVE_MONKEY_TRIAL_PUZZLE_PIECE_4 = "8-K Five Monkey Trial Puzzle Piece (4)"
    FIVE_MONKEY_TRIAL_PUZZLE_PIECE_5 = "8-K Five Monkey Trial Puzzle Piece (5)"
    FIVE_MONKEY_TRIAL_PUZZLE_PIECE_SET = "8-K Five Monkey Trial Puzzle Piece Set"
    FIVE_MONKEY_TRIAL_CLEARED = "8-K Five Monkey Trial cleared"
    FIVE_MONKEY_TRIAL_CLEARED_MIRROR = "8-K Five Monkey Trial cleared (Mirror)"
    FIVE_MONKEY_TRIAL_CLEARED_TIME_TRIAL_BRONZE = "8-K Five Monkey Trial cleared (Time Trial) [Bronze]"
    FIVE_MONKEY_TRIAL_CLEARED_TIME_TRIAL_SILVER = "8-K Five Monkey Trial cleared (Time Trial) [Silver]"
    FIVE_MONKEY_TRIAL_CLEARED_TIME_TRIAL_GOLD = "8-K Five Monkey Trial cleared (Time Trial) [Gold]"

    GOLDEN_TEMPLE_PUZZLE_PIECE_1 = "9-1 Golden Temple Puzzle Piece (1)"
    GOLDEN_TEMPLE_PUZZLE_PIECE_2 = "9-1 Golden Temple Puzzle Piece (2)"
    GOLDEN_TEMPLE_PUZZLE_PIECE_3 = "9-1 Golden Temple Puzzle Piece (3)"
    GOLDEN_TEMPLE_PUZZLE_PIECE_4 = "9-1 Golden Temple Puzzle Piece (4)"
    GOLDEN_TEMPLE_PUZZLE_PIECE_5 = "9-1 Golden Temple Puzzle Piece (5)"
    GOLDEN_TEMPLE_PUZZLE_PIECE_SET = "9-1 Golden Temple Puzzle Piece Set"
    GOLDEN_TEMPLE_MIRROR_MODE_UNLOCK = "9-1 Golden Temple Mirror Mode Unlock"
    GOLDEN_TEMPLE_CLEARED = "9-1 Golden Temple Cleared"
    GOLDEN_TEMPLE_CLEARED_MIRROR = "9-1 Golden Temple Cleared (Mirror)"
    GOLDEN_TEMPLE_CLEARED_TIME_TRIAL_BRONZE = "9-1 Golden Temple Cleared (Time Trial) [Bronze]"
    GOLDEN_TEMPLE_CLEARED_TIME_TRIAL_SILVER = "9-1 Golden Temple Cleared (Time Trial) [Silver]"
    GOLDEN_TEMPLE_CLEARED_TIME_TRIAL_GOLD = "9-1 Golden Temple Cleared (Time Trial) [Gold]"

class Item:

    PUZZLE_PIECE = "Puzzle Piece"

    class Kong_Letter:
        # Jungle
        KONG_LETTER_JUNGLE = "Kong Letter Jungle"

        # Beach
        KONG_LETTER_BEACH = "Kong Letter Beach"

        # Ruins
        KONG_LETTER_RUINS = "Kong Letter Ruins"

        #Cave
        KONG_LETTER_CAVE = "Kong Letter Cave"

        # Forest
        KONG_LETTER_FOREST = "Kong Letter Forest"

        # Cliff
        KONG_LETTER_CLIFF = "Kong Letter Cliff"

        # Factory
        KONG_LETTER_FACTORY = "Kong Letter Factory"

        # Volcano
        KONG_LETTER_VOLCANO = "Kong Letter Volcano"

    class Key:
        JUNGLE_KEY = "Jungle Key"
        Beach_KEY = "Beach Key"
        Ruins_KEY = "Ruins Key"
        CAVE_KEY = "Cave Key"
        FOREST_KEY = "Forest Key"
        CLIFF_KEY = "Cliff Key"
        FACTORY_KEY = "Factory Key"
        VOLCANO_KEY = "Volcano Key"

    class Rare_Orb:
        GREEN_ORB_JUNGLE = "Green Orb Jungle"
        BLUE_ORB_BEACH = "Blue Orb Beach"
        WHITE_ORB_RUINS = "White Orb Ruins"
        MAGENTA_ORB_CAVE = "Magenta Orb Cave"
        YELLOW_ORB_FOREST = "Yellow Orb Forest"
        ORANGE_ORB_CLIFF = "Orange Orb Cliff"
        GRAY_ORB_FACTORY = "Gray Orb Factory"
        RED_ORB_VOLCANO = "Red Orb Volcano"

    class Shop:
        BALLOONX1 = "Balloons x 1"
        BALLOONX3 = "Balloons x 3"
        BALLOONX7 = "Balloons x 7"

    class Unlockables:

        MIRROR_SHARD = "Mirror Shard"

        class Moves:
            RUN = "Run"
            ROLL = "Roll"
            GRAB = "Grab"
            BLOW = "Blow"
            GROUND_POUND = "Ground Pound"

        class MISC:
            ROCKET_BARREL_FUEL = "Rocket Barrel Fuel"
            MINECART_PASS = "Minecart Pass"
            RAMBIS_SADDLE = "Rambi's Saddle"
            KONG_BARREL = "Kong Barrel"
